<?php

function startFilmInfoDataCreation()
{
    return;
    $infosDb = new FilmInfosData();
    $genres = array(

        array("type" => "genres", "value" => "Action"),
        array("type" => "genres", "value" => "Adult"),
        array("type" => "genres", "value" => "Adventure"),
        array("type" => "genres", "value" => "Animation"),
        array("type" => "genres", "value" => "Biography"),
        array("type" => "genres", "value" => "Comedy"),
        array("type" => "genres", "value" => "Crime"),
        array("type" => "genres", "value" => "Documentary"),
        array("type" => "genres", "value" => "Drama"),
        array("type" => "genres", "value" => "Family"),
        array("type" => "genres", "value" => "Fantasy"),
        array("type" => "genres", "value" => "Film-Noir"),
        array("type" => "genres", "value" => "Game-Show"),
        array("type" => "genres", "value" => "History"),
        array("type" => "genres", "value" => "Horror"),
        array("type" => "genres", "value" => "Music"),
        array("type" => "genres", "value" => "Musical"),
        array("type" => "genres", "value" => "Mystery"),
        array("type" => "genres", "value" => "News"),
        array("type" => "genres", "value" => "Reality-TV"),
        array("type" => "genres", "value" => "Romance"),
        array("type" => "genres", "value" => "Sci-Fi"),
        array("type" => "genres", "value" => "Short"),
        array("type" => "genres", "value" => "Sport"),
        array("type" => "genres", "value" => "Talk-Show"),
        array("type" => "genres", "value" => "Thriller"),
        array("type" => "genres", "value" => "War"),
        array("type" => "genres", "value" => "Western"),
    );
    $infosDb->insertBatch($genres);

    $currency = array(

        array("type" => "currency", "value" => "USD U.S. Dollar"),
        array("type" => "currency", "value" => "GBP British Pound"),
        array("type" => "currency", "value" => "EUR Euro"),
        array("type" => "currency", "value" => "ESP Spanish Peseta"),
        array("type" => "currency", "value" => "SEK Swedish Krona"),
        array("type" => "currency", "value" => "CAD Canadian Dollar"),
        array("type" => "currency", "value" => "DEM German Deutsche Mark"),
        array("type" => "currency", "value" => "INR Indian Rupee"),
        array("type" => "currency", "value" => "SGD Singapore Dollar"),
        array("type" => "currency", "value" => "ITL Italian Lira"),
        array("type" => "currency", "value" => "AED UAE Dirham"),
        array("type" => "currency", "value" => "AFA Afghanistan Afghani"),
        array("type" => "currency", "value" => "ALL Albanian Lek"),
        array("type" => "currency", "value" => "AMD Armenian Dram"),
        array("type" => "currency", "value" => "ANG Neth Antilles Guilder"),
        array("type" => "currency", "value" => "AOA Angolan Kwanza"),
        array("type" => "currency", "value" => "ARS Argentine Peso"),
        array("type" => "currency", "value" => "ATS Austrian Schilling"),
        array("type" => "currency", "value" => "AUD Australian Dollar"),
        array("type" => "currency", "value" => "AWG Aruba Florin"),
        array("type" => "currency", "value" => "AZM Azerbaijan Manat"),
        array("type" => "currency", "value" => "BAM Convertible Marka"),
        array("type" => "currency", "value" => "BBD Barbados Dollar"),
        array("type" => "currency", "value" => "BDT Bangladesh Taka"),
        array("type" => "currency", "value" => "BEF Belgium Franc"),
        array("type" => "currency", "value" => "BGL Bulgarian Lev"),
        array("type" => "currency", "value" => "BHD Bahraini Dinar"),
        array("type" => "currency", "value" => "BIF Burundi Franc"),
        array("type" => "currency", "value" => "BMD Bermuda Dollar"),
        array("type" => "currency", "value" => "BND Brunei Dollar"),
        array("type" => "currency", "value" => "BOB Bolivian Boliviano"),
        array("type" => "currency", "value" => "BRL Brazilian Real"),
        array("type" => "currency", "value" => "BSD Bahamian Dollar"),
        array("type" => "currency", "value" => "BTN Bhutan Ngultrum"),
        array("type" => "currency", "value" => "BWP Botswana Pula"),
        array("type" => "currency", "value" => "BYR Belarus Ruble"),
        array("type" => "currency", "value" => "BZD Belize Dollar"),
        array("type" => "currency", "value" => "CAD Canadian Dollar"),
        array("type" => "currency", "value" => "CDF Congolese Francs"),
        array("type" => "currency", "value" => "CHF Swiss Franc"),
        array("type" => "currency", "value" => "CLP Chilean Peso"),
        array("type" => "currency", "value" => "CNY Chinese Yuan"),
        array("type" => "currency", "value" => "COP Colombian Peso"),
        array("type" => "currency", "value" => "CRC Costa Rica Colon"),
        array("type" => "currency", "value" => "CUP Cuban Peso"),
        array("type" => "currency", "value" => "CVE Cape Verde Escudo"),
        array("type" => "currency", "value" => "CYP Cyprus Pound"),
        array("type" => "currency", "value" => "CZK Czech Koruna"),
        array("type" => "currency", "value" => "DEM German Deutsche Mark"),
        array("type" => "currency", "value" => "DJF Dijibouti Franc"),
        array("type" => "currency", "value" => "DKK Danish Krone"),
        array("type" => "currency", "value" => "DOP Dominican Peso"),
        array("type" => "currency", "value" => "DZD Algerian Dinar"),
        array("type" => "currency", "value" => "EEK Estonian Kroon"),
        array("type" => "currency", "value" => "EGP Egyptian Pound"),
        array("type" => "currency", "value" => "ERN Eritrea Nakfa"),
        array("type" => "currency", "value" => "ESP Spanish Peseta"),
        array("type" => "currency", "value" => "ETB Ethiopian Birr"),
        array("type" => "currency", "value" => "EUR Euro"),
        array("type" => "currency", "value" => "FIM Finnish Markka"),
        array("type" => "currency", "value" => "FJD Fiji Dollar"),
        array("type" => "currency", "value" => "FKP Falkland Islands Pound"),
        array("type" => "currency", "value" => "FRF French Franc"),
        array("type" => "currency", "value" => "GBP British Pound"),
        array("type" => "currency", "value" => "GEL Georgian Lari"),
        array("type" => "currency", "value" => "GGP Guernsey Pounds"),
        array("type" => "currency", "value" => "GHC Ghanian Cedi"),
        array("type" => "currency", "value" => "GIP Gibraltar Pound"),
        array("type" => "currency", "value" => "GMD Gambian Dalasi"),
        array("type" => "currency", "value" => "GNF Guinea Franc"),
        array("type" => "currency", "value" => "GRD Greek Drachma"),
        array("type" => "currency", "value" => "GTQ Guatemala Quetzal"),
        array("type" => "currency", "value" => "GYD Guyana Dollar"),
        array("type" => "currency", "value" => "HKD Hong Kong Dollar"),
        array("type" => "currency", "value" => "HNL Honduras Lempira"),
        array("type" => "currency", "value" => "HRK Croatian Kuna"),
        array("type" => "currency", "value" => "HTG Haiti Gourde"),
        array("type" => "currency", "value" => "HUF Hungarian Forint"),
        array("type" => "currency", "value" => "IDR Indonesian Rupiah"),
        array("type" => "currency", "value" => "IEP Irish Pound"),
        array("type" => "currency", "value" => "ILS Israeli Shekel"),
        array("type" => "currency", "value" => "IMP Isle of Man Pounds"),
        array("type" => "currency", "value" => "INR Indian Rupee"),
        array("type" => "currency", "value" => "IQD Iraqi Dinar"),
        array("type" => "currency", "value" => "IRR Iran Rial"),
        array("type" => "currency", "value" => "ISK Iceland Krona"),
        array("type" => "currency", "value" => "ITL Italian Lira"),
        array("type" => "currency", "value" => "JEP Jersey Pounds"),
        array("type" => "currency", "value" => "JMD Jamaican Dollar"),
        array("type" => "currency", "value" => "JOD Jordanian Dinar"),
        array("type" => "currency", "value" => "JPY Japanese Yen"),
        array("type" => "currency", "value" => "KES Kenyan Shilling"),
        array("type" => "currency", "value" => "KGS Kyrgyzstan Soms"),
        array("type" => "currency", "value" => "KHR Cambodia Riel"),
        array("type" => "currency", "value" => "KMF Comoros Franc"),
        array("type" => "currency", "value" => "KPW North Korean Won"),
        array("type" => "currency", "value" => "KRW Korean Won"),
        array("type" => "currency", "value" => "KWD Kuwaiti Dinar"),
        array("type" => "currency", "value" => "KYD Cayman Islands Dollar"),
        array("type" => "currency", "value" => "KZT Kazakhstan Tenge"),
        array("type" => "currency", "value" => "LAK Lao Kip"),
        array("type" => "currency", "value" => "LBP Lebanese Pound"),
        array("type" => "currency", "value" => "LKR Sri Lanka Rupee"),
        array("type" => "currency", "value" => "LRD Liberian Dollar"),
        array("type" => "currency", "value" => "LSL Lesotho Loti"),
        array("type" => "currency", "value" => "LTL Lithuanian Lita"),
        array("type" => "currency", "value" => "LUF Luxembourg Franc"),
        array("type" => "currency", "value" => "LVL Latvian Lat"),
        array("type" => "currency", "value" => "LYD Libyan Dinar"),
        array("type" => "currency", "value" => "MAD Moroccan Dirham"),
        array("type" => "currency", "value" => "MDL Moldovan Leu"),
        array("type" => "currency", "value" => "MGF Malagasy Franc"),
        array("type" => "currency", "value" => "MKD Macedonian Denar"),
        array("type" => "currency", "value" => "MMK Myanmar Kyat"),
        array("type" => "currency", "value" => "MNT Mongolian Tugrik"),
        array("type" => "currency", "value" => "MOP Macau Pataca"),
        array("type" => "currency", "value" => "MRO Mauritania Ougulya"),
        array("type" => "currency", "value" => "MTL Maltese Lira"),
        array("type" => "currency", "value" => "MUR Mauritius Rupee"),
        array("type" => "currency", "value" => "MVR Maldives Rufiyaa"),
        array("type" => "currency", "value" => "MWK Malawi Kwacha"),
        array("type" => "currency", "value" => "MXN Mexican Peso"),
        array("type" => "currency", "value" => "MYR Malaysian Ringgit"),
        array("type" => "currency", "value" => "MZM Mozambique Metical"),
        array("type" => "currency", "value" => "NAD Namibian Dollar"),
        array("type" => "currency", "value" => "NGN Nigerian Naira"),
        array("type" => "currency", "value" => "NIO Nicaragua Cordoba"),
        array("type" => "currency", "value" => "NLG Netherlands Guilder"),
        array("type" => "currency", "value" => "NOK Norwegian Krone"),
        array("type" => "currency", "value" => "NPR Nepalese Rupee"),
        array("type" => "currency", "value" => "NZD New Zealand Dollar"),
        array("type" => "currency", "value" => "OMR Omani Rial"),
        array("type" => "currency", "value" => "PAB Panama Balboa"),
        array("type" => "currency", "value" => "PEN Peruvian Nuevo Sol"),
        array("type" => "currency", "value" => "PGK Papua New Guinea Kina"),
        array("type" => "currency", "value" => "PHP Philippine Peso"),
        array("type" => "currency", "value" => "PKR Pakistani Rupee"),
        array("type" => "currency", "value" => "PLN Polish Zloty"),
        array("type" => "currency", "value" => "PTE Portuguese Escudo"),
        array("type" => "currency", "value" => "PYG Paraguayan Guarani"),
        array("type" => "currency", "value" => "QAR Qatar Rial"),
        array("type" => "currency", "value" => "ROL Romanian Leu"),
        array("type" => "currency", "value" => "RON Romanian New Leu"),
        array("type" => "currency", "value" => "RUR Russian Rouble"),
        array("type" => "currency", "value" => "RWF Rwanda Franc"),
        array("type" => "currency", "value" => "SAR Saudi Arabian Riyal"),
        array("type" => "currency", "value" => "SBD Solomon Islands Dollar"),
        array("type" => "currency", "value" => "SCR Seychelles Rupee"),
        array("type" => "currency", "value" => "SDD Sudanese Dinar"),
        array("type" => "currency", "value" => "SEK Swedish Krona"),
        array("type" => "currency", "value" => "SGD Singapore Dollar"),
        array("type" => "currency", "value" => "SHP St Helena Pound"),
        array("type" => "currency", "value" => "SIT Slovenian Tolar"),
        array("type" => "currency", "value" => "SKK Slovak Koruna"),
        array("type" => "currency", "value" => "SLL Sierra Leone Leone"),
        array("type" => "currency", "value" => "SOS Somali Shilling"),
        array("type" => "currency", "value" => "SPL Seborga Luigini"),
        array("type" => "currency", "value" => "SRG Surinam Guilder"),
        array("type" => "currency", "value" => "STD Sao Tome Dobra"),
        array("type" => "currency", "value" => "SVC El Salvador Colon"),
        array("type" => "currency", "value" => "SYP Syrian Pound"),
        array("type" => "currency", "value" => "SZL Swaziland Lilageni"),
        array("type" => "currency", "value" => "THB Thai Baht"),
        array("type" => "currency", "value" => "TJS Tajikistan Somoni"),
        array("type" => "currency", "value" => "TMM Turkmenistan Manats"),
        array("type" => "currency", "value" => "TND Tunisian Dinar"),
        array("type" => "currency", "value" => "TOP Tonga Pa'anga"),
        array("type" => "currency", "value" => "TRL Turkish Lira"),
        array("type" => "currency", "value" => "TTD Trinidad &amp; Tobago Dollar"),
        array("type" => "currency", "value" => "TVD Tuvalu Dollars"),
        array("type" => "currency", "value" => "TWD Taiwan Dollar"),
        array("type" => "currency", "value" => "TZS Tanzanian Shilling"),
        array("type" => "currency", "value" => "UAH Ukraine Hryvnia"),
        array("type" => "currency", "value" => "UGX Ugandan Shilling"),
        array("type" => "currency", "value" => "USD U.S. Dollar"),
        array("type" => "currency", "value" => "UYU Uruguayan New Peso"),
        array("type" => "currency", "value" => "UZS Uzbekistan Sums"),
        array("type" => "currency", "value" => "VAL Vatican City Lira"),
        array("type" => "currency", "value" => "VEB Venezuelan Bolivar"),
        array("type" => "currency", "value" => "VND Vietnam Dong"),
        array("type" => "currency", "value" => "VUV Vanuatu Vatu"),
        array("type" => "currency", "value" => "WST Samoa Tala"),
        array("type" => "currency", "value" => "XAF CFA Franc (BEAC)"),
        array("type" => "currency", "value" => "XAG Silver Ounces"),
        array("type" => "currency", "value" => "XAU Gold Ounces"),
        array("type" => "currency", "value" => "XCD East Caribbean Dollar"),
        array("type" => "currency", "value" => "XDR IMF Special Drawing Rights"),
        array("type" => "currency", "value" => "XOF CFA Franc (BCEAO)"),
        array("type" => "currency", "value" => "XPD Palladium Ounces"),
        array("type" => "currency", "value" => "XPF Pacific Franc"),
        array("type" => "currency", "value" => "XPT Platinum Ounces"),
        array("type" => "currency", "value" => "YER Yemen Riyal"),
        array("type" => "currency", "value" => "YUM Yugoslav Dinar"),
        array("type" => "currency", "value" => "ZAR South African Rand"),
        array("type" => "currency", "value" => "ZMK Zambian Kwacha"),
        array("type" => "currency", "value" => "ZWD Zimbabwe Dollar"),
    );
    $infosDb->insertBatch($currency);
}