<?php


function startFilmInfoDataCreation()
{
    return;
    $infosDb = new FilmInfosData();

    $producer_type = array(
        array("type" => "producer_type", "value" => "producer"),
        array("type" => "producer_type", "value" => "executive producer"),
        array("type" => "producer_type", "value" => "associate producer"),
        array("type" => "producer_type", "value" => "supervising producer"),
        array("type" => "producer_type", "value" => "co-producer"),
        array("type" => "producer_type", "value" => "line producer"),
        array("type" => "producer_type", "value" => "co-executive producer"),
        array("type" => "producer_type", "value" => "assistant producer"),
        array("type" => "producer_type", "value" => "series producer"),
        array("type" => "producer_type", "value" => "coordinating producer"),
        array("type" => "producer_type", "value" => "Other (use box below)")
    );
    $infosDb->insertBatch($producer_type);
    
    $sound_mix = array(
        array("type" => "sound_mix", "value" => "Mono"),
        array("type" => "sound_mix", "value" => "Stereo"),
        array("type" => "sound_mix", "value" => "Silent"),
        array("type" => "sound_mix", "value" => "Dolby Digital"),
        array("type" => "sound_mix", "value" => "Dolby"),
        array("type" => "sound_mix", "value" => "Dolby SR"),
        array("type" => "sound_mix", "value" => "DTS"),
        array("type" => "sound_mix", "value" => "SDDS"),
        array("type" => "sound_mix", "value" => "12-Track Digital Sound"),
        array("type" => "sound_mix", "value" => "3 Channel Stereo"),
        array("type" => "sound_mix", "value" => "4-Track Stereo"),
        array("type" => "sound_mix", "value" => "6-Track Stereo"),
        array("type" => "sound_mix", "value" => "70 mm 6-Track"),
        array("type" => "sound_mix", "value" => "Afifa Ton-Kopie"),
        array("type" => "sound_mix", "value" => "AGA Sound System"),
        array("type" => "sound_mix", "value" => "Animatophone"),
        array("type" => "sound_mix", "value" => "Auro 11.1"),
        array("type" => "sound_mix", "value" => "Auro 9.1"),
        array("type" => "sound_mix", "value" => "Aurofone"),
        array("type" => "sound_mix", "value" => "B.A.F. Sound System"),
        array("type" => "sound_mix", "value" => "Blue Seal Noiseless Recording"),
        array("type" => "sound_mix", "value" => "Bristolphone"),
        array("type" => "sound_mix", "value" => "Broadway Surround"),
        array("type" => "sound_mix", "value" => "CDS"),
        array("type" => "sound_mix", "value" => "Chace Surround"),
        array("type" => "sound_mix", "value" => "Chronophone"),
        array("type" => "sound_mix", "value" => "Cinematophone"),
        array("type" => "sound_mix", "value" => "Cineophone"),
        array("type" => "sound_mix", "value" => "Cinephone"),
        array("type" => "sound_mix", "value" => "Cinerama 7-Track"),
        array("type" => "sound_mix", "value" => "Cinesound"),
        array("type" => "sound_mix", "value" => "D-Cinema 48kHz 5.1"),
        array("type" => "sound_mix", "value" => "D-Cinema 48kHz 7.1"),
        array("type" => "sound_mix", "value" => "D-Cinema 48kHz Dolby Surround 7.1"),
        array("type" => "sound_mix", "value" => "D-Cinema 96kHz 5.1"),
        array("type" => "sound_mix", "value" => "D-Cinema 96kHz 7.1"),
        array("type" => "sound_mix", "value" => "D-Cinema 96kHz Dolby Surround 7.1"),
        array("type" => "sound_mix", "value" => "Datasat"),
        array("type" => "sound_mix", "value" => "De Forest Phonofilm"),
        array("type" => "sound_mix", "value" => "Digitrac Digital Audio System"),
        array("type" => "sound_mix", "value" => "Dolby"),
        array("type" => "sound_mix", "value" => "Dolby Atmos"),
        array("type" => "sound_mix", "value" => "Dolby Digital"),
        array("type" => "sound_mix", "value" => "Dolby Digital EX"),
        array("type" => "sound_mix", "value" => "Dolby SR"),
        array("type" => "sound_mix", "value" => "Dolby Stereo"),
        array("type" => "sound_mix", "value" => "Dolby Surround 7.1"),
        array("type" => "sound_mix", "value" => "DTS"),
        array("type" => "sound_mix", "value" => "DTS 70 mm"),
        array("type" => "sound_mix", "value" => "DTS-8"),
        array("type" => "sound_mix", "value" => "DTS-ES"),
        array("type" => "sound_mix", "value" => "DTS-Stereo"),
        array("type" => "sound_mix", "value" => "DX Stereo"),
        array("type" => "sound_mix", "value" => "Filmtone"),
        array("type" => "sound_mix", "value" => "Full Range Recording System"),
        array("type" => "sound_mix", "value" => "Gaumontphone"),
        array("type" => "sound_mix", "value" => "IMAX 6-Track"),
        array("type" => "sound_mix", "value" => "International Recording Engineers System"),
        array("type" => "sound_mix", "value" => "Iwerks Digital Audio"),
        array("type" => "sound_mix", "value" => "Kinetophone"),
        array("type" => "sound_mix", "value" => "Kinopanorama 9-Track"),
        array("type" => "sound_mix", "value" => "Kinoplasticon"),
        array("type" => "sound_mix", "value" => "Klangfilm Magnetocord"),
        array("type" => "sound_mix", "value" => "Klangfilm-Stereocord"),
        array("type" => "sound_mix", "value" => "LC-Concept Digital Sound"),
        array("type" => "sound_mix", "value" => "Li-Westrex System"),
        array("type" => "sound_mix", "value" => "Magnaphone Western Electric"),
        array("type" => "sound_mix", "value" => "Magnetocord"),
        array("type" => "sound_mix", "value" => "Matrix Surround"),
        array("type" => "sound_mix", "value" => "Mono"),
        array("type" => "sound_mix", "value" => "Optiphone"),
        array("type" => "sound_mix", "value" => "Ortiphone"),
        array("type" => "sound_mix", "value" => "Perspecta Stereo"),
        array("type" => "sound_mix", "value" => "Phillips Sound"),
        array("type" => "sound_mix", "value" => "Phono-Cinema-Theatre"),
        array("type" => "sound_mix", "value" => "Phono-Kinema"),
        array("type" => "sound_mix", "value" => "Phonofilm"),
        array("type" => "sound_mix", "value" => "Pulvári System"),
        array("type" => "sound_mix", "value" => "Quadrophonic"),
        array("type" => "sound_mix", "value" => "Quintaphonic"),
        array("type" => "sound_mix", "value" => "SDDS"),
        array("type" => "sound_mix", "value" => "Sensurround"),
        array("type" => "sound_mix", "value" => "Servotron Stereo"),
        array("type" => "sound_mix", "value" => "Silent"),
        array("type" => "sound_mix", "value" => "Sonics"),
        array("type" => "sound_mix", "value" => "Sonics-DDP"),
        array("type" => "sound_mix", "value" => "Sonix"),
        array("type" => "sound_mix", "value" => "Sonora-Bristolphone"),
        array("type" => "sound_mix", "value" => "Sound 360°"),
        array("type" => "sound_mix", "value" => "Sound Trax Surround Stereo"),
        array("type" => "sound_mix", "value" => "Soundelux"),
        array("type" => "sound_mix", "value" => "Spectra-Stereo"),
        array("type" => "sound_mix", "value" => "Stereo"),
        array("type" => "sound_mix", "value" => "Super Space Sound"),
        array("type" => "sound_mix", "value" => "Synchrotone"),
        array("type" => "sound_mix", "value" => "Synthetic"),
        array("type" => "sound_mix", "value" => "Systemi A. Shorin"),
        array("type" => "sound_mix", "value" => "Système Cottet"),
        array("type" => "sound_mix", "value" => "Tagephone"),
        array("type" => "sound_mix", "value" => "TMH Labs 10.2 Channel Sound"),
        array("type" => "sound_mix", "value" => "Tri-Ergon Sound System"),
        array("type" => "sound_mix", "value" => "Ultra Stereo"),
        array("type" => "sound_mix", "value" => "Variray Blue Seal Recording"),
        array("type" => "sound_mix", "value" => "Visatone"),
        array("type" => "sound_mix", "value" => "Vistasonic"),
        array("type" => "sound_mix", "value" => "Vitaphone"),
        array("type" => "sound_mix", "value" => "Vivaphone"),
        array("type" => "sound_mix", "value" => "Wicmar and Blue Seal Noiseless Recording")
    );
    $infosDb->insertBatch($sound_mix);
    
    $sound_mix_attribute = array(
        array("type" => "sound_mix_attribute", "value" => "(RCA Sound Recording)"),
        array("type" => "sound_mix_attribute", "value" => "(Westrex Recording System)"),
        array("type" => "sound_mix_attribute", "value" => "(RCA Sound System)"),
        array("type" => "sound_mix_attribute", "value" => "(Western Electric Recording)"),
        array("type" => "sound_mix_attribute", "value" => "(Western Electric Sound System)"),
        array("type" => "sound_mix_attribute", "value" => "Other (use box below)")
    );
    $infosDb->insertBatch($sound_mix_attribute);
    
    $aspect_ratio = array(
        array("type" => "aspect_ratio", "value" => "1.33 : 1"),
        array("type" => "aspect_ratio", "value" => "16:9 HD"),
        array("type" => "aspect_ratio", "value" => "2.35 : 1"),
        array("type" => "aspect_ratio", "value" => "1.85 : 1"),
        array("type" => "aspect_ratio", "value" => "1.37 : 1"),
        array("type" => "aspect_ratio", "value" => "1.78 : 1"),
        array("type" => "aspect_ratio", "value" => "4:3"),
        array("type" => "aspect_ratio", "value" => "1.66 : 1"),
        array("type" => "aspect_ratio", "value" => "1.78 : 1 / (high definition)"),
        array("type" => "aspect_ratio", "value" => "16 : 9"),
        array("type" => "aspect_ratio", "value" => "Other (use box below)")
    );
    $infosDb->insertBatch($aspect_ratio);
    
    $certificates = array(
        array("type" => "certificates", "value" => "USA:12"),
        array("type" => "certificates", "value" => "USA:AO"),
        array("type" => "certificates", "value" => "USA:Approved"),
        array("type" => "certificates", "value" => "USA:Banned"),
        array("type" => "certificates", "value" => "USA:EC"),
        array("type" => "certificates", "value" => "USA:E"),
        array("type" => "certificates", "value" => "USA:E10+"),
        array("type" => "certificates", "value" => "USA:G"),
        array("type" => "certificates", "value" => "USA:GA"),
        array("type" => "certificates", "value" => "USA:GP"),
        array("type" => "certificates", "value" => "USA:K-A"),
        array("type" => "certificates", "value" => "USA:M"),
        array("type" => "certificates", "value" => "USA:M/PG"),
        array("type" => "certificates", "value" => "USA:MA-13"),
        array("type" => "certificates", "value" => "USA:MA-17"),
        array("type" => "certificates", "value" => "USA:NC-17"),
        array("type" => "certificates", "value" => "USA:Not Rated"),
        array("type" => "certificates", "value" => "USA:Open"),
        array("type" => "certificates", "value" => "USA:Passed"),
        array("type" => "certificates", "value" => "USA:PG"),
        array("type" => "certificates", "value" => "USA:PG-13"),
        array("type" => "certificates", "value" => "USA:R"),
        array("type" => "certificates", "value" => "USA:T"),
        array("type" => "certificates", "value" => "USA:TV-13"),
        array("type" => "certificates", "value" => "USA:TV-14"),
        array("type" => "certificates", "value" => "USA:TV-G"),
        array("type" => "certificates", "value" => "USA:TV-MA"),
        array("type" => "certificates", "value" => "USA:TV-PG"),
        array("type" => "certificates", "value" => "USA:TV-Y"),
        array("type" => "certificates", "value" => "USA:TV-Y7"),
        array("type" => "certificates", "value" => "USA:TV-Y7-FV"),
        array("type" => "certificates", "value" => "USA:Unrated"),
        array("type" => "certificates", "value" => "USA:X"),
        array("type" => "certificates", "value" => "Argentina:0"),
        array("type" => "certificates", "value" => "Argentina:7"),
        array("type" => "certificates", "value" => "Argentina:10"),
        array("type" => "certificates", "value" => "Argentina:12"),
        array("type" => "certificates", "value" => "Argentina:13"),
        array("type" => "certificates", "value" => "Argentina:14"),
        array("type" => "certificates", "value" => "Argentina:16"),
        array("type" => "certificates", "value" => "Argentina:18"),
        array("type" => "certificates", "value" => "Argentina:Atp"),
        array("type" => "certificates", "value" => "Argentina:E"),
        array("type" => "certificates", "value" => "Argentina:M"),
        array("type" => "certificates", "value" => "Argentina:RP"),
        array("type" => "certificates", "value" => "Argentina:T"),
        array("type" => "certificates", "value" => "Argentina:Unrated"),
        array("type" => "certificates", "value" => "Argentina:X"),
        array("type" => "certificates", "value" => "Australasia:E"),
        array("type" => "certificates", "value" => "Australia:A"),
        array("type" => "certificates", "value" => "Australia:E"),
        array("type" => "certificates", "value" => "Australia:G"),
        array("type" => "certificates", "value" => "Australia:G8+"),
        array("type" => "certificates", "value" => "Australia:M"),
        array("type" => "certificates", "value" => "Australia:MA"),
        array("type" => "certificates", "value" => "Australia:MA15+"),
        array("type" => "certificates", "value" => "Australia:M15+"),
        array("type" => "certificates", "value" => "Australia:MA-15"),
        array("type" => "certificates", "value" => "Australia:NRC"),
        array("type" => "certificates", "value" => "Australia:PG"),
        array("type" => "certificates", "value" => "Australia:R"),
        array("type" => "certificates", "value" => "Australia:R18+"),
        array("type" => "certificates", "value" => "Australia:RC"),
        array("type" => "certificates", "value" => "Australia:Revoked"),
        array("type" => "certificates", "value" => "Australia:SOA"),
        array("type" => "certificates", "value" => "Australia:X"),
        array("type" => "certificates", "value" => "Australia:X18+"),
        array("type" => "certificates", "value" => "Australia:7+"),
        array("type" => "certificates", "value" => "Australia:13+"),
        array("type" => "certificates", "value" => "Australia:16+"),
        array("type" => "certificates", "value" => "Australia:18+"),
        array("type" => "certificates", "value" => "Austria:(Banned)"),
        array("type" => "certificates", "value" => "Austria:0"),
        array("type" => "certificates", "value" => "Austria:10"),
        array("type" => "certificates", "value" => "Austria:12"),
        array("type" => "certificates", "value" => "Austria:14"),
        array("type" => "certificates", "value" => "Austria:16"),
        array("type" => "certificates", "value" => "Austria:18"),
        array("type" => "certificates", "value" => "Austria:6"),
        array("type" => "certificates", "value" => "Austria:8"),
        array("type" => "certificates", "value" => "Belgium:KNT/ENA"),
        array("type" => "certificates", "value" => "Belgium:KT/EA"),
        array("type" => "certificates", "value" => "Belgium:AL/Tous"),
        array("type" => "certificates", "value" => "Belgium:6"),
        array("type" => "certificates", "value" => "Belgium:9"),
        array("type" => "certificates", "value" => "Belgium:12"),
        array("type" => "certificates", "value" => "Belgium:14"),
        array("type" => "certificates", "value" => "Belgium:16"),
        array("type" => "certificates", "value" => "Belgium:18"),
        array("type" => "certificates", "value" => "Brazil:(Banned)"),
        array("type" => "certificates", "value" => "Brazil:10"),
        array("type" => "certificates", "value" => "Brazil:12"),
        array("type" => "certificates", "value" => "Brazil:14"),
        array("type" => "certificates", "value" => "Brazil:16"),
        array("type" => "certificates", "value" => "Brazil:18"),
        array("type" => "certificates", "value" => "Brazil:Livre"),
        array("type" => "certificates", "value" => "Brazil:Not Rated"),
        array("type" => "certificates", "value" => "Bulgaria:A"),
        array("type" => "certificates", "value" => "Bulgaria:B"),
        array("type" => "certificates", "value" => "Bulgaria:C"),
        array("type" => "certificates", "value" => "Bulgaria:D"),
        array("type" => "certificates", "value" => "Bulgaria:X"),
        array("type" => "certificates", "value" => "Canada:(Banned)"),
        array("type" => "certificates", "value" => "Canada:13+"),
        array("type" => "certificates", "value" => "Canada:14"),
        array("type" => "certificates", "value" => "Canada:14+"),
        array("type" => "certificates", "value" => "Canada:14A"),
        array("type" => "certificates", "value" => "Canada:16+"),
        array("type" => "certificates", "value" => "Canada:18"),
        array("type" => "certificates", "value" => "Canada:18+"),
        array("type" => "certificates", "value" => "Canada:18A"),
        array("type" => "certificates", "value" => "Canada:A"),
        array("type" => "certificates", "value" => "Canada:AA"),
        array("type" => "certificates", "value" => "Canada:C"),
        array("type" => "certificates", "value" => "Canada:C8"),
        array("type" => "certificates", "value" => "Canada:E"),
        array("type" => "certificates", "value" => "Canada:F"),
        array("type" => "certificates", "value" => "Canada:G"),
        array("type" => "certificates", "value" => "Canada:NC-17"),
        array("type" => "certificates", "value" => "Canada:PA"),
        array("type" => "certificates", "value" => "Canada:PG"),
        array("type" => "certificates", "value" => "Canada:PG-13"),
        array("type" => "certificates", "value" => "Canada:R"),
        array("type" => "certificates", "value" => "Canada:RX"),
        array("type" => "certificates", "value" => "Canada:TV-G"),
        array("type" => "certificates", "value" => "Canada:TV-MA"),
        array("type" => "certificates", "value" => "Canada:TV-PG"),
        array("type" => "certificates", "value" => "Canada:TV-Y"),
        array("type" => "certificates", "value" => "Canada:TV-Y7"),
        array("type" => "certificates", "value" => "Canada:TV-Y7-FV"),
        array("type" => "certificates", "value" => "Canada:TV-14"),
        array("type" => "certificates", "value" => "Canada:XXX"),
        array("type" => "certificates", "value" => "Canada:Not Rated"),
        array("type" => "certificates", "value" => "Chile:(Banned)"),
        array("type" => "certificates", "value" => "Chile:13+"),
        array("type" => "certificates", "value" => "Chile:14"),
        array("type" => "certificates", "value" => "Chile:16+"),
        array("type" => "certificates", "value" => "Chile:18"),
        array("type" => "certificates", "value" => "Chile:A"),
        array("type" => "certificates", "value" => "Chile:F"),
        array("type" => "certificates", "value" => "Chile:I"),
        array("type" => "certificates", "value" => "Chile:I12"),
        array("type" => "certificates", "value" => "Chile:I7"),
        array("type" => "certificates", "value" => "Chile:R"),
        array("type" => "certificates", "value" => "Chile:TE"),
        array("type" => "certificates", "value" => "Chile:TE+7"),
        array("type" => "certificates", "value" => "China:(Banned)"),
        array("type" => "certificates", "value" => "China:13"),
        array("type" => "certificates", "value" => "China:17"),
        array("type" => "certificates", "value" => "Colombia:12"),
        array("type" => "certificates", "value" => "Colombia:15"),
        array("type" => "certificates", "value" => "Colombia:18"),
        array("type" => "certificates", "value" => "Colombia:7"),
        array("type" => "certificates", "value" => "Colombia:T"),
        array("type" => "certificates", "value" => "Colombia:X"),
        array("type" => "certificates", "value" => "Costa Rica:TP"),
        array("type" => "certificates", "value" => "Costa Rica:TP7"),
        array("type" => "certificates", "value" => "Costa Rica:TP12+"),
        array("type" => "certificates", "value" => "Costa Rica:12+"),
        array("type" => "certificates", "value" => "Costa Rica:15+"),
        array("type" => "certificates", "value" => "Costa Rica:18+"),
        array("type" => "certificates", "value" => "Costa Rica:Recomendado"),
        array("type" => "certificates", "value" => "Cyprus:Cat. 3"),
        array("type" => "certificates", "value" => "Czech Republic:12"),
        array("type" => "certificates", "value" => "Czech Republic:15"),
        array("type" => "certificates", "value" => "Czech Republic:18"),
        array("type" => "certificates", "value" => "Czech Republic:8+"),
        array("type" => "certificates", "value" => "Czech Republic:U"),
        array("type" => "certificates", "value" => "Czechoslovakia:(Banned)"),
        array("type" => "certificates", "value" => "Denmark:(Banned)"),
        array("type" => "certificates", "value" => "Denmark:11"),
        array("type" => "certificates", "value" => "Denmark:12"),
        array("type" => "certificates", "value" => "Denmark:15"),
        array("type" => "certificates", "value" => "Denmark:16"),
        array("type" => "certificates", "value" => "Denmark:7"),
        array("type" => "certificates", "value" => "Denmark:A"),
        array("type" => "certificates", "value" => "Ecuador:Not Rated"),
        array("type" => "certificates", "value" => "Ecuador:ALL"),
        array("type" => "certificates", "value" => "Ecuador:A"),
        array("type" => "certificates", "value" => "Ecuador:B"),
        array("type" => "certificates", "value" => "Ecuador:C"),
        array("type" => "certificates", "value" => "Ecuador:TP"),
        array("type" => "certificates", "value" => "Ecuador:7+"),
        array("type" => "certificates", "value" => "Ecuador:12"),
        array("type" => "certificates", "value" => "Ecuador:13+"),
        array("type" => "certificates", "value" => "Ecuador:15"),
        array("type" => "certificates", "value" => "Ecuador:16"),
        array("type" => "certificates", "value" => "Ecuador:18"),
        array("type" => "certificates", "value" => "East Germany:(Banned)"),
        array("type" => "certificates", "value" => "Egypt:(Banned)"),
        array("type" => "certificates", "value" => "Egypt:G"),
        array("type" => "certificates", "value" => "Egypt:E"),
        array("type" => "certificates", "value" => "Egypt:7+"),
        array("type" => "certificates", "value" => "Egypt:8+"),
        array("type" => "certificates", "value" => "Egypt:12+"),
        array("type" => "certificates", "value" => "Egypt:13+"),
        array("type" => "certificates", "value" => "Egypt:16+"),
        array("type" => "certificates", "value" => "Egypt:18+"),
        array("type" => "certificates", "value" => "Egypt:R"),
        array("type" => "certificates", "value" => "Egypt:R-12"),
        array("type" => "certificates", "value" => "Egypt:PG"),
        array("type" => "certificates", "value" => "Egypt:PG-12"),
        array("type" => "certificates", "value" => "Egypt:PG-13"),
        array("type" => "certificates", "value" => "Egypt:Not Rated"),
        array("type" => "certificates", "value" => "Egypt:All ages"),
        array("type" => "certificates", "value" => "Finland:(Banned)"),
        array("type" => "certificates", "value" => "Finland:K-10"),
        array("type" => "certificates", "value" => "Finland:K-10/7"),
        array("type" => "certificates", "value" => "Finland:K-10/8"),
        array("type" => "certificates", "value" => "Finland:K-11"),
        array("type" => "certificates", "value" => "Finland:K-11/9"),
        array("type" => "certificates", "value" => "Finland:K-12"),
        array("type" => "certificates", "value" => "Finland:K-12/9"),
        array("type" => "certificates", "value" => "Finland:K-13"),
        array("type" => "certificates", "value" => "Finland:K-14"),
        array("type" => "certificates", "value" => "Finland:K-15"),
        array("type" => "certificates", "value" => "Finland:K-15/13"),
        array("type" => "certificates", "value" => "Finland:K-16"),
        array("type" => "certificates", "value" => "Finland:K-16/13"),
        array("type" => "certificates", "value" => "Finland:K-18"),
        array("type" => "certificates", "value" => "Finland:K-3"),
        array("type" => "certificates", "value" => "Finland:K-6"),
        array("type" => "certificates", "value" => "Finland:K-6/3"),
        array("type" => "certificates", "value" => "Finland:K-6/4"),
        array("type" => "certificates", "value" => "Finland:K-7"),
        array("type" => "certificates", "value" => "Finland:K-7/4"),
        array("type" => "certificates", "value" => "Finland:K-7/5"),
        array("type" => "certificates", "value" => "Finland:K-8"),
        array("type" => "certificates", "value" => "Finland:K-8/5"),
        array("type" => "certificates", "value" => "Finland:K-8/6"),
        array("type" => "certificates", "value" => "Finland:S/T"),
        array("type" => "certificates", "value" => "Finland:S"),
        array("type" => "certificates", "value" => "France:Accord parental"),
        array("type" => "certificates", "value" => "France:Tous publics"),
        array("type" => "certificates", "value" => "France:Tous publics avec avertissement"),
        array("type" => "certificates", "value" => "France:0+"),
        array("type" => "certificates", "value" => "France:6+"),
        array("type" => "certificates", "value" => "France:7"),
        array("type" => "certificates", "value" => "France:9+"),
        array("type" => "certificates", "value" => "France:10"),
        array("type" => "certificates", "value" => "France:10 avec avertissement"),
        array("type" => "certificates", "value" => "France:12"),
        array("type" => "certificates", "value" => "France:12 avec avertissement"),
        array("type" => "certificates", "value" => "France:13"),
        array("type" => "certificates", "value" => "France:14+"),
        array("type" => "certificates", "value" => "France:16"),
        array("type" => "certificates", "value" => "France:16 avec avertissement"),
        array("type" => "certificates", "value" => "France:18"),
        array("type" => "certificates", "value" => "France:X"),
        array("type" => "certificates", "value" => "France:(Banned)"),
        array("type" => "certificates", "value" => "France:Not Rated"),
        array("type" => "certificates", "value" => "France:Public Averti"),
        array("type" => "certificates", "value" => "Germany:(Banned)"),
        array("type" => "certificates", "value" => "Germany:0"),
        array("type" => "certificates", "value" => "Germany:12"),
        array("type" => "certificates", "value" => "Germany:13"),
        array("type" => "certificates", "value" => "Germany:16"),
        array("type" => "certificates", "value" => "Germany:18"),
        array("type" => "certificates", "value" => "Germany:6"),
        array("type" => "certificates", "value" => "Germany:Infoprogramm gemäß § 14 JuSchG"),
        array("type" => "certificates", "value" => "Germany:Not Rated"),
        array("type" => "certificates", "value" => "Greece:A-18"),
        array("type" => "certificates", "value" => "Greece:K"),
        array("type" => "certificates", "value" => "Greece:K-8"),
        array("type" => "certificates", "value" => "Greece:K-10"),
        array("type" => "certificates", "value" => "Greece:K-12"),
        array("type" => "certificates", "value" => "Greece:K-13"),
        array("type" => "certificates", "value" => "Greece:K-15"),
        array("type" => "certificates", "value" => "Greece:K-16"),
        array("type" => "certificates", "value" => "Greece:K-17"),
        array("type" => "certificates", "value" => "Hong Kong:Not Rated"),
        array("type" => "certificates", "value" => "Hong Kong::All"),
        array("type" => "certificates", "value" => "Hong Kong:I"),
        array("type" => "certificates", "value" => "Hong Kong:II"),
        array("type" => "certificates", "value" => "Hong Kong:IIA"),
        array("type" => "certificates", "value" => "Hong Kong:IIB"),
        array("type" => "certificates", "value" => "Hong Kong:III"),
        array("type" => "certificates", "value" => "Hong Kong:7+"),
        array("type" => "certificates", "value" => "Hong Kong:13+"),
        array("type" => "certificates", "value" => "Hong Kong:16+"),
        array("type" => "certificates", "value" => "Hong Kong:18+"),
        array("type" => "certificates", "value" => "Hungary:12"),
        array("type" => "certificates", "value" => "Hungary:14"),
        array("type" => "certificates", "value" => "Hungary:16"),
        array("type" => "certificates", "value" => "Hungary:18"),
        array("type" => "certificates", "value" => "Hungary:6"),
        array("type" => "certificates", "value" => "Hungary:KN"),
        array("type" => "certificates", "value" => "Iceland:(Banned)"),
        array("type" => "certificates", "value" => "Iceland:10"),
        array("type" => "certificates", "value" => "Iceland:12"),
        array("type" => "certificates", "value" => "Iceland:14"),
        array("type" => "certificates", "value" => "Iceland:16"),
        array("type" => "certificates", "value" => "Iceland:18"),
        array("type" => "certificates", "value" => "Iceland:7"),
        array("type" => "certificates", "value" => "Iceland:L"),
        array("type" => "certificates", "value" => "Iceland:LH"),
        array("type" => "certificates", "value" => "Iceland:Unrated"),
        array("type" => "certificates", "value" => "India:(Banned)"),
        array("type" => "certificates", "value" => "India:All"),
        array("type" => "certificates", "value" => "India:A"),
        array("type" => "certificates", "value" => "India:PG"),
        array("type" => "certificates", "value" => "India:U"),
        array("type" => "certificates", "value" => "India:UA"),
        array("type" => "certificates", "value" => "India:UA 7+"),
        array("type" => "certificates", "value" => "India:UA 13+"),
        array("type" => "certificates", "value" => "India:UA 16+"),
        array("type" => "certificates", "value" => "India:7"),
        array("type" => "certificates", "value" => "India:12+"),
        array("type" => "certificates", "value" => "India:13"),
        array("type" => "certificates", "value" => "India:15+"),
        array("type" => "certificates", "value" => "India:16"),
        array("type" => "certificates", "value" => "India:18"),
        array("type" => "certificates", "value" => "India:Not Rated"),
        array("type" => "certificates", "value" => "Indonesia:Not Rated"),
        array("type" => "certificates", "value" => "Indonesia:PG"),
        array("type" => "certificates", "value" => "Indonesia:7+"),
        array("type" => "certificates", "value" => "Indonesia:13+"),
        array("type" => "certificates", "value" => "Indonesia:15"),
        array("type" => "certificates", "value" => "Indonesia:16+"),
        array("type" => "certificates", "value" => "Indonesia:17+"),
        array("type" => "certificates", "value" => "Indonesia:18+"),
        array("type" => "certificates", "value" => "Indonesia:20+"),
        array("type" => "certificates", "value" => "Indonesia:21"),
        array("type" => "certificates", "value" => "Indonesia:21+"),
        array("type" => "certificates", "value" => "Indonesia:A"),
        array("type" => "certificates", "value" => "Indonesia:D"),
        array("type" => "certificates", "value" => "Indonesia:D17+"),
        array("type" => "certificates", "value" => "Indonesia:D21+"),
        array("type" => "certificates", "value" => "Indonesia:P"),
        array("type" => "certificates", "value" => "Indonesia:R"),
        array("type" => "certificates", "value" => "Indonesia:G"),
        array("type" => "certificates", "value" => "Indonesia:R13+"),
        array("type" => "certificates", "value" => "Indonesia:SU"),
        array("type" => "certificates", "value" => "Indonesia:R:BO"),
        array("type" => "certificates", "value" => "Indonesia:A:BO"),
        array("type" => "certificates", "value" => "Indonesia:P:BO"),
        array("type" => "certificates", "value" => "Indonesia:Semua"),
        array("type" => "certificates", "value" => "Iran:(Banned)"),
        array("type" => "certificates", "value" => "Iran:18+"),
        array("type" => "certificates", "value" => "Iraq:(Banned)"),
        array("type" => "certificates", "value" => "Ireland:(Banned)"),
        array("type" => "certificates", "value" => "Ireland:12"),
        array("type" => "certificates", "value" => "Ireland:12A"),
        array("type" => "certificates", "value" => "Ireland:12PG"),
        array("type" => "certificates", "value" => "Ireland:12RA"),
        array("type" => "certificates", "value" => "Ireland:15"),
        array("type" => "certificates", "value" => "Ireland:15A"),
        array("type" => "certificates", "value" => "Ireland:15PG"),
        array("type" => "certificates", "value" => "Ireland:16"),
        array("type" => "certificates", "value" => "Ireland:18"),
        array("type" => "certificates", "value" => "Ireland:G"),
        array("type" => "certificates", "value" => "Ireland:PG"),
        array("type" => "certificates", "value" => "Israel:ALL"),
        array("type" => "certificates", "value" => "Israel:Not Rated"),
        array("type" => "certificates", "value" => "Israel:7+"),
        array("type" => "certificates", "value" => "Israel:8+"),
        array("type" => "certificates", "value" => "Israel:12"),
        array("type" => "certificates", "value" => "Israel:13"),
        array("type" => "certificates", "value" => "Israel:14"),
        array("type" => "certificates", "value" => "Israel:15+"),
        array("type" => "certificates", "value" => "Israel:16"),
        array("type" => "certificates", "value" => "Israel:18"),
        array("type" => "certificates", "value" => "Israel:PG"),
        array("type" => "certificates", "value" => "Israel:X"),
        array("type" => "certificates", "value" => "Italy:(Banned)"),
        array("type" => "certificates", "value" => "Italy:T"),
        array("type" => "certificates", "value" => "Italy: BA"),
        array("type" => "certificates", "value" => "Italy:Not Rated"),
        array("type" => "certificates", "value" => "Italy:VM12"),
        array("type" => "certificates", "value" => "Italy:VM14"),
        array("type" => "certificates", "value" => "Italy:VM16"),
        array("type" => "certificates", "value" => "Italy:VM18"),
        array("type" => "certificates", "value" => "Italy:6+"),
        array("type" => "certificates", "value" => "Japan:Not Rated"),
        array("type" => "certificates", "value" => "Japan:(Banned)"),
        array("type" => "certificates", "value" => "Japan:12"),
        array("type" => "certificates", "value" => "Japan:15"),
        array("type" => "certificates", "value" => "Japan:16+"),
        array("type" => "certificates", "value" => "Japan:18"),
        array("type" => "certificates", "value" => "Japan:A"),
        array("type" => "certificates", "value" => "Japan:Adult Movie"),
        array("type" => "certificates", "value" => "Japan:All Ages"),
        array("type" => "certificates", "value" => "Japan:B"),
        array("type" => "certificates", "value" => "Japan:C"),
        array("type" => "certificates", "value" => "Japan:D"),
        array("type" => "certificates", "value" => "Japan:G"),
        array("type" => "certificates", "value" => "Japan:PG-12"),
        array("type" => "certificates", "value" => "Japan:PG12"),
        array("type" => "certificates", "value" => "Japan:R"),
        array("type" => "certificates", "value" => "Japan:R-15"),
        array("type" => "certificates", "value" => "Japan:R-18"),
        array("type" => "certificates", "value" => "Japan:R15+"),
        array("type" => "certificates", "value" => "Japan:R18+"),
        array("type" => "certificates", "value" => "Japan:Unrated"),
        array("type" => "certificates", "value" => "Japan:Z"),
        array("type" => "certificates", "value" => "Kuwait:(Banned)"),
        array("type" => "certificates", "value" => "Lebanon:(Banned)"),
        array("type" => "certificates", "value" => "Lithuania:N-13"),
        array("type" => "certificates", "value" => "Lithuania:N-16"),
        array("type" => "certificates", "value" => "Lithuania:N-18"),
        array("type" => "certificates", "value" => "Lithuania:N-7"),
        array("type" => "certificates", "value" => "Lithuania:V"),
        array("type" => "certificates", "value" => "Luxembourg:12"),
        array("type" => "certificates", "value" => "Luxembourg:16"),
        array("type" => "certificates", "value" => "Luxembourg:17"),
        array("type" => "certificates", "value" => "Luxembourg:18"),
        array("type" => "certificates", "value" => "Luxembourg:6"),
        array("type" => "certificates", "value" => "Luxembourg:A"),
        array("type" => "certificates", "value" => "Malaysia:(Banned)"),
        array("type" => "certificates", "value" => "Malaysia:18"),
        array("type" => "certificates", "value" => "Malaysia:18PL"),
        array("type" => "certificates", "value" => "Malaysia:18SG"),
        array("type" => "certificates", "value" => "Malaysia:18SX"),
        array("type" => "certificates", "value" => "Malaysia:P13"),
        array("type" => "certificates", "value" => "Malaysia:U"),
        array("type" => "certificates", "value" => "Maldives:(Banned)"),
        array("type" => "certificates", "value" => "Maldives:12+"),
        array("type" => "certificates", "value" => "Maldives:15+"),
        array("type" => "certificates", "value" => "Maldives:18+"),
        array("type" => "certificates", "value" => "Maldives:18+R"),
        array("type" => "certificates", "value" => "Maldives:G"),
        array("type" => "certificates", "value" => "Maldives:PG"),
        array("type" => "certificates", "value" => "Maldives:PU"),
        array("type" => "certificates", "value" => "Malta:12"),
        array("type" => "certificates", "value" => "Malta:12A"),
        array("type" => "certificates", "value" => "Malta:15"),
        array("type" => "certificates", "value" => "Malta:16"),
        array("type" => "certificates", "value" => "Malta:18"),
        array("type" => "certificates", "value" => "Malta:PG"),
        array("type" => "certificates", "value" => "Malta:U"),
        array("type" => "certificates", "value" => "Mexico:A"),
        array("type" => "certificates", "value" => "Mexico:AA"),
        array("type" => "certificates", "value" => "Mexico:B"),
        array("type" => "certificates", "value" => "Mexico:B15"),
        array("type" => "certificates", "value" => "Mexico:C"),
        array("type" => "certificates", "value" => "Mexico:D"),
        array("type" => "certificates", "value" => "Mexico: G"),
        array("type" => "certificates", "value" => "Mexico:TV-Y"),
        array("type" => "certificates", "value" => "Mexico:TV-G"),
        array("type" => "certificates", "value" => "Mexico:PG"),
        array("type" => "certificates", "value" => "Mexico:TV-Y7"),
        array("type" => "certificates", "value" => "Mexico:TV-Y7-FV"),
        array("type" => "certificates", "value" => "Mexico:TV-PG"),
        array("type" => "certificates", "value" => "Mexico:PG-13"),
        array("type" => "certificates", "value" => "Mexico:TV-14"),
        array("type" => "certificates", "value" => "Mexico:R"),
        array("type" => "certificates", "value" => "Mexico:NC-17"),
        array("type" => "certificates", "value" => "Mexico:TV-MA"),
        array("type" => "certificates", "value" => "Mexico:S/C"),
        array("type" => "certificates", "value" => "Mexico:0+"),
        array("type" => "certificates", "value" => "Mexico:9+"),
        array("type" => "certificates", "value" => "Mexico:12+"),
        array("type" => "certificates", "value" => "Mexico:18+"),
        array("type" => "certificates", "value" => "Mexico:TODO"),
        array("type" => "certificates", "value" => "Mexico:7"),
        array("type" => "certificates", "value" => "Mexico:13"),
        array("type" => "certificates", "value" => "Mexico:16"),
        array("type" => "certificates", "value" => "Mexico:18"),
        array("type" => "certificates", "value" => "Mongolia:PG"),
        array("type" => "certificates", "value" => "Netherlands:12"),
        array("type" => "certificates", "value" => "Netherlands:14"),
        array("type" => "certificates", "value" => "Netherlands:16"),
        array("type" => "certificates", "value" => "Netherlands:18"),
        array("type" => "certificates", "value" => "Netherlands:6"),
        array("type" => "certificates", "value" => "Netherlands:7+"),
        array("type" => "certificates", "value" => "Netherlands:9"),
        array("type" => "certificates", "value" => "Netherlands:13+"),
        array("type" => "certificates", "value" => "Netherlands:AL"),
        array("type" => "certificates", "value" => "Netherlands:MG6"),
        array("type" => "certificates", "value" => "Netherlands:Unrated"),
        array("type" => "certificates", "value" => "New Zealand:AO"),
        array("type" => "certificates", "value" => "New Zealand:(Banned)"),
        array("type" => "certificates", "value" => "New Zealand:G"),
        array("type" => "certificates", "value" => "New Zealand:M"),
        array("type" => "certificates", "value" => "New Zealand:Objectionable"),
        array("type" => "certificates", "value" => "New Zealand:PG"),
        array("type" => "certificates", "value" => "New Zealand:R"),
        array("type" => "certificates", "value" => "New Zealand:R13"),
        array("type" => "certificates", "value" => "New Zealand:R15"),
        array("type" => "certificates", "value" => "New Zealand:R16"),
        array("type" => "certificates", "value" => "New Zealand:R18"),
        array("type" => "certificates", "value" => "New Zealand:RP13"),
        array("type" => "certificates", "value" => "New Zealand:RP16"),
        array("type" => "certificates", "value" => "New Zealand:RP18"),
        array("type" => "certificates", "value" => "Nigeria:12"),
        array("type" => "certificates", "value" => "Nigeria:12A"),
        array("type" => "certificates", "value" => "Nigeria:15"),
        array("type" => "certificates", "value" => "Nigeria:18"),
        array("type" => "certificates", "value" => "Nigeria:G"),
        array("type" => "certificates", "value" => "Nigeria:PG"),
        array("type" => "certificates", "value" => "Nigeria:RE"),
        array("type" => "certificates", "value" => "Norway:(Banned)"),
        array("type" => "certificates", "value" => "Norway:10"),
        array("type" => "certificates", "value" => "Norway:11"),
        array("type" => "certificates", "value" => "Norway:12"),
        array("type" => "certificates", "value" => "Norway:15"),
        array("type" => "certificates", "value" => "Norway:16"),
        array("type" => "certificates", "value" => "Norway:18"),
        array("type" => "certificates", "value" => "Norway:5"),
        array("type" => "certificates", "value" => "Norway:7"),
        array("type" => "certificates", "value" => "Norway:9"),
        array("type" => "certificates", "value" => "Norway:A"),
        array("type" => "certificates", "value" => "Norway:Banned"),
        array("type" => "certificates", "value" => "Peru:14"),
        array("type" => "certificates", "value" => "Peru:18"),
        array("type" => "certificates", "value" => "Peru:Apt"),
        array("type" => "certificates", "value" => "Philippines :All"),
        array("type" => "certificates", "value" => "Philippines:(Banned)"),
        array("type" => "certificates", "value" => "Philippines:G"),
        array("type" => "certificates", "value" => "Philippines :PG"),
        array("type" => "certificates", "value" => "Philippines:PG-13"),
        array("type" => "certificates", "value" => "Philippines:R-13"),
        array("type" => "certificates", "value" => "Philippines:R-16"),
        array("type" => "certificates", "value" => "Philippines:R-18"),
        array("type" => "certificates", "value" => "Philippines :7+"),
        array("type" => "certificates", "value" => "Philippines :13+"),
        array("type" => "certificates", "value" => "Philippines :14"),
        array("type" => "certificates", "value" => "Philippines :16+"),
        array("type" => "certificates", "value" => "Philippines :18+"),
        array("type" => "certificates", "value" => "Philippines:SPG"),
        array("type" => "certificates", "value" => "Philippines:U"),
        array("type" => "certificates", "value" => "Philippines:X"),
        array("type" => "certificates", "value" => "Poland:(Banned)"),
        array("type" => "certificates", "value" => "Poland:All"),
        array("type" => "certificates", "value" => "Poland:0"),
        array("type" => "certificates", "value" => "Poland:6"),
        array("type" => "certificates", "value" => "Poland:10+"),
        array("type" => "certificates", "value" => "Poland:12"),
        array("type" => "certificates", "value" => "Poland:13"),
        array("type" => "certificates", "value" => "Poland:15"),
        array("type" => "certificates", "value" => "Poland:16"),
        array("type" => "certificates", "value" => "Poland:18"),
        array("type" => "certificates", "value" => "Poland:7"),
        array("type" => "certificates", "value" => "Poland:b.o."),
        array("type" => "certificates", "value" => "Poland:NC"),
        array("type" => "certificates", "value" => "Poland:G"),
        array("type" => "certificates", "value" => "Portugal:(Banned)"),
        array("type" => "certificates", "value" => "Portugal:10AP"),
        array("type" => "certificates", "value" => "Portugal:12AP"),
        array("type" => "certificates", "value" => "Portugal:16"),
        array("type" => "certificates", "value" => "Portugal:17"),
        array("type" => "certificates", "value" => "Portugal:M/12"),
        array("type" => "certificates", "value" => "Portugal:M/14"),
        array("type" => "certificates", "value" => "Portugal:M/16"),
        array("type" => "certificates", "value" => "Portugal:M/18"),
        array("type" => "certificates", "value" => "Portugal:M/3"),
        array("type" => "certificates", "value" => "Portugal:M/4"),
        array("type" => "certificates", "value" => "Portugal:M/6"),
        array("type" => "certificates", "value" => "Portugal:T"),
        array("type" => "certificates", "value" => "Puerto Rico:PG"),
        array("type" => "certificates", "value" => "Puerto Rico:PG-13"),
        array("type" => "certificates", "value" => "Romania:A.G."),
        array("type" => "certificates", "value" => "Romania:I.C.-14"),
        array("type" => "certificates", "value" => "Romania:I.M.-18"),
        array("type" => "certificates", "value" => "Russia:(Banned)"),
        array("type" => "certificates", "value" => "Russia:0+"),
        array("type" => "certificates", "value" => "Russia:12+"),
        array("type" => "certificates", "value" => "Russia:14+"),
        array("type" => "certificates", "value" => "Russia:16+"),
        array("type" => "certificates", "value" => "Russia:18+"),
        array("type" => "certificates", "value" => "Russia:6+"),
        array("type" => "certificates", "value" => "Saudi Arabia:R18"),
        array("type" => "certificates", "value" => "Saudi Arabia:R15"),
        array("type" => "certificates", "value" => "Saudi Arabia:R12"),
        array("type" => "certificates", "value" => "Saudi Arabia:PG12"),
        array("type" => "certificates", "value" => "Saudi Arabia:PG"),
        array("type" => "certificates", "value" => "Saudi Arabia:G"),
        array("type" => "certificates", "value" => "Saudi Arabia:Not Rated"),
        array("type" => "certificates", "value" => "Saudi Arabia:(Banned)"),
        array("type" => "certificates", "value" => "Serbia:12"),
        array("type" => "certificates", "value" => "Singapore:(Banned)"),
        array("type" => "certificates", "value" => "Singapore:ADV"),
        array("type" => "certificates", "value" => "Singapore:ADV16"),
        array("type" => "certificates", "value" => "Singapore:G"),
        array("type" => "certificates", "value" => "Singapore:15"),
        array("type" => "certificates", "value" => "Singapore:M18"),
        array("type" => "certificates", "value" => "Singapore:NC-16"),
        array("type" => "certificates", "value" => "Singapore:NC16"),
        array("type" => "certificates", "value" => "Singapore:PG"),
        array("type" => "certificates", "value" => "Singapore:PG13"),
        array("type" => "certificates", "value" => "Singapore:R(A)"),
        array("type" => "certificates", "value" => "Singapore:R21"),
        array("type" => "certificates", "value" => "Singapore:Unrated"),
        array("type" => "certificates", "value" => "Slovakia:12"),
        array("type" => "certificates", "value" => "Slovenia:15+"),
        array("type" => "certificates", "value" => "South Africa:(Banned)"),
        array("type" => "certificates", "value" => "South Africa:(Seized)"),
        array("type" => "certificates", "value" => "South Africa:10"),
        array("type" => "certificates", "value" => "South Africa:10-12"),
        array("type" => "certificates", "value" => "South Africa:10-12PG"),
        array("type" => "certificates", "value" => "South Africa:13"),
        array("type" => "certificates", "value" => "South Africa:16"),
        array("type" => "certificates", "value" => "South Africa:18"),
        array("type" => "certificates", "value" => "South Africa:7-9"),
        array("type" => "certificates", "value" => "South Africa:7-9PG"),
        array("type" => "certificates", "value" => "South Africa:A"),
        array("type" => "certificates", "value" => "South Africa:PG"),
        array("type" => "certificates", "value" => "South Africa:X18"),
        array("type" => "certificates", "value" => "South Africa:XX"),
        array("type" => "certificates", "value" => "South Korea:(Banned)"),
        array("type" => "certificates", "value" => "South Korea:12"),
        array("type" => "certificates", "value" => "South Korea:15"),
        array("type" => "certificates", "value" => "South Korea:18"),
        array("type" => "certificates", "value" => "South Korea:19"),
        array("type" => "certificates", "value" => "South Korea:7"),
        array("type" => "certificates", "value" => "South Korea:All"),
        array("type" => "certificates", "value" => "South Korea:Limited"),
        array("type" => "certificates", "value" => "South Korea:Youth not allowed"),
        array("type" => "certificates", "value" => "South Korea:13+"),
        array("type" => "certificates", "value" => "South Korea:16+"),
        array("type" => "certificates", "value" => "Soviet Union:(Banned)"),
        array("type" => "certificates", "value" => "Soviet Union:16"),
        array("type" => "certificates", "value" => "Spain:A"),
        array("type" => "certificates", "value" => "Spain:A/fig"),
        array("type" => "certificates", "value" => "Spain:A/i"),
        array("type" => "certificates", "value" => "Spain:A/i/fig"),
        array("type" => "certificates", "value" => "Spain:TP"),
        array("type" => "certificates", "value" => "Spain:0+"),
        array("type" => "certificates", "value" => "Spain:3"),
        array("type" => "certificates", "value" => "Spain:4+"),
        array("type" => "certificates", "value" => "Spain:6+"),
        array("type" => "certificates", "value" => "Spain:7"),
        array("type" => "certificates", "value" => "Spain:7/fig"),
        array("type" => "certificates", "value" => "Spain:7/i"),
        array("type" => "certificates", "value" => "Spain:7/i/fig"),
        array("type" => "certificates", "value" => "Spain:9+"),
        array("type" => "certificates", "value" => "Spain:10"),
        array("type" => "certificates", "value" => "Spain:12"),
        array("type" => "certificates", "value" => "Spain:12/fig"),
        array("type" => "certificates", "value" => "Spain:13"),
        array("type" => "certificates", "value" => "Spain:14"),
        array("type" => "certificates", "value" => "Spain:16"),
        array("type" => "certificates", "value" => "Spain:16/fig"),
        array("type" => "certificates", "value" => "Spain:18"),
        array("type" => "certificates", "value" => "Spain:18/fig"),
        array("type" => "certificates", "value" => "Spain:S"),
        array("type" => "certificates", "value" => "Spain:X"),
        array("type" => "certificates", "value" => "Spain: Apta para mayores"),
        array("type" => "certificates", "value" => "Spain:Not Rated"),
        array("type" => "certificates", "value" => "Spain:(Banned)"),
        array("type" => "certificates", "value" => "Sweden:(Banned)"),
        array("type" => "certificates", "value" => "Sweden:All"),
        array("type" => "certificates", "value" => "Sweden:Alla"),
        array("type" => "certificates", "value" => "Sweden:0+"),
        array("type" => "certificates", "value" => "Sweden:7"),
        array("type" => "certificates", "value" => "Sweden:7+"),
        array("type" => "certificates", "value" => "Sweden:9"),
        array("type" => "certificates", "value" => "Sweden:9+"),
        array("type" => "certificates", "value" => "Sweden:10+"),
        array("type" => "certificates", "value" => "Sweden:11"),
        array("type" => "certificates", "value" => "Sweden:12"),
        array("type" => "certificates", "value" => "Sweden:13"),
        array("type" => "certificates", "value" => "Sweden:14"),
        array("type" => "certificates", "value" => "Sweden:15"),
        array("type" => "certificates", "value" => "Sweden:16+"),
        array("type" => "certificates", "value" => "Sweden:18"),
        array("type" => "certificates", "value" => "Sweden:18+"),
        array("type" => "certificates", "value" => "Sweden:Btl"),
        array("type" => "certificates", "value" => "Sweden:IK"),
        array("type" => "certificates", "value" => "Sweden:OK"),
        array("type" => "certificates", "value" => "Switzerland:0"),
        array("type" => "certificates", "value" => "Switzerland:10"),
        array("type" => "certificates", "value" => "Switzerland:12"),
        array("type" => "certificates", "value" => "Switzerland:14"),
        array("type" => "certificates", "value" => "Switzerland:16"),
        array("type" => "certificates", "value" => "Switzerland:18"),
        array("type" => "certificates", "value" => "Switzerland:6"),
        array("type" => "certificates", "value" => "Switzerland:7"),
        array("type" => "certificates", "value" => "Switzerland:8"),
        array("type" => "certificates", "value" => "Switzerland:9"),
        array("type" => "certificates", "value" => "Taiwan:ALL"),
        array("type" => "certificates", "value" => "Taiwan:6+"),
        array("type" => "certificates", "value" => "Taiwan:7+"),
        array("type" => "certificates", "value" => "Taiwan:13+"),
        array("type" => "certificates", "value" => "Taiwan:16+"),
        array("type" => "certificates", "value" => "Taiwan:18+"),
        array("type" => "certificates", "value" => "Taiwan:G"),
        array("type" => "certificates", "value" => "Taiwan:P"),
        array("type" => "certificates", "value" => "Taiwan:R"),
        array("type" => "certificates", "value" => "Taiwan:GP"),
        array("type" => "certificates", "value" => "Taiwan:PG-12"),
        array("type" => "certificates", "value" => "Taiwan:R-12"),
        array("type" => "certificates", "value" => "Taiwan:R-15"),
        array("type" => "certificates", "value" => "Taiwan:R-18"),
        array("type" => "certificates", "value" => "Taiwan:PG"),
        array("type" => "certificates", "value" => "Taiwan:PG-15"),
        array("type" => "certificates", "value" => "Thailand:ALL"),
        array("type" => "certificates", "value" => "Thailand:(Banned)"),
        array("type" => "certificates", "value" => "Thailand:Not Rated"),
        array("type" => "certificates", "value" => "Thailand:C"),
        array("type" => "certificates", "value" => "Thailand:E"),
        array("type" => "certificates", "value" => "Thailand:G"),
        array("type" => "certificates", "value" => "Thailand:U"),
        array("type" => "certificates", "value" => "Thailand:3+"),
        array("type" => "certificates", "value" => "Thailand:6+"),
        array("type" => "certificates", "value" => "Thailand:7+"),
        array("type" => "certificates", "value" => "Thailand:13"),
        array("type" => "certificates", "value" => "Thailand:13+"),
        array("type" => "certificates", "value" => "Thailand:15"),
        array("type" => "certificates", "value" => "Thailand:15+"),
        array("type" => "certificates", "value" => "Thailand:16+"),
        array("type" => "certificates", "value" => "Thailand:18"),
        array("type" => "certificates", "value" => "Thailand:18+"),
        array("type" => "certificates", "value" => "Thailand:20"),
        array("type" => "certificates", "value" => "Thailand:G"),
        array("type" => "certificates", "value" => "Thailand:P"),
        array("type" => "certificates", "value" => "Thailand:PG-13"),
        array("type" => "certificates", "value" => "Thailand:PD-14"),
        array("type" => "certificates", "value" => "Thailand:R-14"),
        array("type" => "certificates", "value" => "Turkey:Not Rated"),
        array("type" => "certificates", "value" => "Turkey:Genel İzleyici Kitlesi"),
        array("type" => "certificates", "value" => "Turkey:6A"),
        array("type" => "certificates", "value" => "Turkey:6+"),
        array("type" => "certificates", "value" => "Turkey:7A"),
        array("type" => "certificates", "value" => "Turkey:10A"),
        array("type" => "certificates", "value" => "Turkey:10+"),
        array("type" => "certificates", "value" => "Turkey:13+"),
        array("type" => "certificates", "value" => "Turkey:13A"),
        array("type" => "certificates", "value" => "Turkey:15+"),
        array("type" => "certificates", "value" => "Turkey:15A"),
        array("type" => "certificates", "value" => "Turkey:16+"),
        array("type" => "certificates", "value" => "Turkey:18+"),
        array("type" => "certificates", "value" => "Turkey:7+"),
        array("type" => "certificates", "value" => "Turkey:G"),
        array("type" => "certificates", "value" => "UK:(Banned)"),
        array("type" => "certificates", "value" => "UK:Caution"),
        array("type" => "certificates", "value" => "UK:0+"),
        array("type" => "certificates", "value" => "UK:3+"),
        array("type" => "certificates", "value" => "UK:6+"),
        array("type" => "certificates", "value" => "UK:7+"),
        array("type" => "certificates", "value" => "UK:9+"),
        array("type" => "certificates", "value" => "UK:11+"),
        array("type" => "certificates", "value" => "UK:12"),
        array("type" => "certificates", "value" => "UK:12A"),
        array("type" => "certificates", "value" => "UK:13+"),
        array("type" => "certificates", "value" => "UK:14+"),
        array("type" => "certificates", "value" => "UK:15"),
        array("type" => "certificates", "value" => "UK:16"),
        array("type" => "certificates", "value" => "UK:18"),
        array("type" => "certificates", "value" => "UK:7"),
        array("type" => "certificates", "value" => "UK:A"),
        array("type" => "certificates", "value" => "UK:AA"),
        array("type" => "certificates", "value" => "UK:All"),
        array("type" => "certificates", "value" => "UK:Adult"),
        array("type" => "certificates", "value" => "UK:E"),
        array("type" => "certificates", "value" => "UK:G"),
        array("type" => "certificates", "value" => "UK:H"),
        array("type" => "certificates", "value" => "UK:Mature"),
        array("type" => "certificates", "value" => "UK:Not Rated"),
        array("type" => "certificates", "value" => "UK:NR"),
        array("type" => "certificates", "value" => "UK:PG"),
        array("type" => "certificates", "value" => "UK:PG-13"),
        array("type" => "certificates", "value" => "UK:R18"),
        array("type" => "certificates", "value" => "UK:Rejected"),
        array("type" => "certificates", "value" => "UK:Teen"),
        array("type" => "certificates", "value" => "UK:U"),
        array("type" => "certificates", "value" => "UK:Uc"),
        array("type" => "certificates", "value" => "UK:X"),
        array("type" => "certificates", "value" => "Ukraine:12"),
        array("type" => "certificates", "value" => "Ukraine:16"),
        array("type" => "certificates", "value" => "Ukraine:18"),
        array("type" => "certificates", "value" => "Ukraine:DA"),
        array("type" => "certificates", "value" => "Ukraine:ZA"),
        array("type" => "certificates", "value" => "Ukraine:(Banned)"),
        array("type" => "certificates", "value" => "United Arab Emirates:All"),
        array("type" => "certificates", "value" => "United Arab Emirates:G"),
        array("type" => "certificates", "value" => "United Arab Emirates:PG"),
        array("type" => "certificates", "value" => "United Arab Emirates:0+"),
        array("type" => "certificates", "value" => "United Arab Emirates:7+"),
        array("type" => "certificates", "value" => "United Arab Emirates:12+"),
        array("type" => "certificates", "value" => "United Arab Emirates:13+"),
        array("type" => "certificates", "value" => "United Arab Emirates:15+"),
        array("type" => "certificates", "value" => "United Arab Emirates:16+"),
        array("type" => "certificates", "value" => "United Arab Emirates:18+"),
        array("type" => "certificates", "value" => "United Arab Emirates:TBA-15+"),
        array("type" => "certificates", "value" => "United Arab Emirates:PG-12"),
        array("type" => "certificates", "value" => "United Arab Emirates:PG-13"),
        array("type" => "certificates", "value" => "United Arab Emirates:PG-15"),
        array("type" => "certificates", "value" => "United Arab Emirates:R"),
        array("type" => "certificates", "value" => "United Arab Emirates:16D"),
        array("type" => "certificates", "value" => "United Arab Emirates:FAM"),
        array("type" => "certificates", "value" => "United Arab Emirates:PG-12"),
        array("type" => "certificates", "value" => "United Arab Emirates:U"),
        array("type" => "certificates", "value" => "United Arab Emirates:18TC"),
        array("type" => "certificates", "value" => "United Arab Emirates:TBC"),
        array("type" => "certificates", "value" => "United Arab Emirates:Not Rated"),
        array("type" => "certificates", "value" => "USA:12"),
        array("type" => "certificates", "value" => "USA:AO"),
        array("type" => "certificates", "value" => "USA:Approved"),
        array("type" => "certificates", "value" => "USA:Banned"),
        array("type" => "certificates", "value" => "USA:EC"),
        array("type" => "certificates", "value" => "USA:E"),
        array("type" => "certificates", "value" => "USA:E10+"),
        array("type" => "certificates", "value" => "USA:G"),
        array("type" => "certificates", "value" => "USA:GA"),
        array("type" => "certificates", "value" => "USA:GP"),
        array("type" => "certificates", "value" => "USA:K-A"),
        array("type" => "certificates", "value" => "USA:M"),
        array("type" => "certificates", "value" => "USA:M/PG"),
        array("type" => "certificates", "value" => "USA:MA-13"),
        array("type" => "certificates", "value" => "USA:MA-17"),
        array("type" => "certificates", "value" => "USA:NC-17"),
        array("type" => "certificates", "value" => "USA:Not Rated"),
        array("type" => "certificates", "value" => "USA:Open"),
        array("type" => "certificates", "value" => "USA:Passed"),
        array("type" => "certificates", "value" => "USA:PG"),
        array("type" => "certificates", "value" => "USA:PG-13"),
        array("type" => "certificates", "value" => "USA:R"),
        array("type" => "certificates", "value" => "USA:T"),
        array("type" => "certificates", "value" => "USA:TV-13"),
        array("type" => "certificates", "value" => "USA:TV-14"),
        array("type" => "certificates", "value" => "USA:TV-G"),
        array("type" => "certificates", "value" => "USA:TV-MA"),
        array("type" => "certificates", "value" => "USA:TV-PG"),
        array("type" => "certificates", "value" => "USA:TV-Y"),
        array("type" => "certificates", "value" => "USA:TV-Y7"),
        array("type" => "certificates", "value" => "USA:TV-Y7-FV"),
        array("type" => "certificates", "value" => "USA:Unrated"),
        array("type" => "certificates", "value" => "USA:X"),
        array("type" => "certificates", "value" => "Venezuela:PG-13"),
        array("type" => "certificates", "value" => "Vietnam:(Banned)"),
        array("type" => "certificates", "value" => "Vietnam:P"),
        array("type" => "certificates", "value" => "Vietnam:C13"),
        array("type" => "certificates", "value" => "Vietnam:C16"),
        array("type" => "certificates", "value" => "Vietnam:C18"),
        array("type" => "certificates", "value" => "West Germany:(Banned)"),
        array("type" => "certificates", "value" => "West Germany:0"),
        array("type" => "certificates", "value" => "West Germany:12"),
        array("type" => "certificates", "value" => "West Germany:16"),
        array("type" => "certificates", "value" => "West Germany:18"),
        array("type" => "certificates", "value" => "West Germany:6"),
        array("type" => "certificates", "value" => "West Germany:Not Rated")
    );
    $infosDb->insertBatch($certificates);

}
