<?php

// producerTypes
$producerTypes = array(
    "producer",
    "executive producer",
    "associate producer",
    "supervising producer",
    "co-producer",
    "line producer",
    "co-executive producer",
    "assistant producer",
    "series producer",
    "coordinating producer",
    "Other (use box below)",
);

$certificates = array(
    "USA:12",
    "USA:AO",
    "USA:Approved",
    "USA:Banned",
    "USA:EC",
    "USA:E",
    "USA:E10+",
    "USA:G",
    "USA:GA",
    "USA:GP",
    "USA:K-A",
    "USA:M",
    "USA:M/PG",
    "USA:MA-13",
    "USA:MA-17",
    "USA:NC-17",
    "USA:Not Rated",
    "USA:Open",
    "USA:Passed",
    "USA:PG",
    "USA:PG-13",
    "USA:R",
    "USA:T",
    "USA:TV-13",
    "USA:TV-14",
    "USA:TV-G",
    "USA:TV-MA",
    "USA:TV-PG",
    "USA:TV-Y",
    "USA:TV-Y7",
    "USA:TV-Y7-FV",
    "USA:Unrated",
    "USA:X",
    "Argentina:0",
    "Argentina:7",
    "Argentina:10",
    "Argentina:12",
    "Argentina:13",
    "Argentina:14",
    "Argentina:16",
    "Argentina:18",
    "Argentina:Atp",
    "Argentina:E",
    "Argentina:M",
    "Argentina:RP",
    "Argentina:T",
    "Argentina:Unrated",
    "Argentina:X",
    "Australasia:E",
    "Australia:A",
    "Australia:E",
    "Australia:G",
    "Australia:G8+",
    "Australia:M",
    "Australia:MA",
    "Australia:MA15+",
    "Australia:M15+",
    "Australia:MA-15",
    "Australia:NRC",
    "Australia:PG",
    "Australia:R",
    "Australia:R18+",
    "Australia:RC",
    "Australia:Revoked",
    "Australia:SOA",
    "Australia:X",
    "Australia:X18+",
    "Australia:7+",
    "Australia:13+",
    "Australia:16+",
    "Australia:18+",
    "Austria:(Banned)",
    "Austria:0",
    "Austria:10",
    "Austria:12",
    "Austria:14",
    "Austria:16",
    "Austria:18",
    "Austria:6",
    "Austria:8",
    "Belgium:KNT/ENA",
    "Belgium:KT/EA",
    "Belgium:AL/Tous",
    "Belgium:6",
    "Belgium:9",
    "Belgium:12",
    "Belgium:14",
    "Belgium:16",
    "Belgium:18",
    "Brazil:(Banned)",
    "Brazil:10",
    "Brazil:12",
    "Brazil:14",
    "Brazil:16",
    "Brazil:18",
    "Brazil:Livre",
    "Brazil:Not Rated",
    "Bulgaria:A",
    "Bulgaria:B",
    "Bulgaria:C",
    "Bulgaria:D",
    "Bulgaria:X",
    "Canada:(Banned)",
    "Canada:13+",
    "Canada:14",
    "Canada:14+",
    "Canada:14A",
    "Canada:16+",
    "Canada:18",
    "Canada:18+",
    "Canada:18A",
    "Canada:A",
    "Canada:AA",
    "Canada:C",
    "Canada:C8",
    "Canada:E",
    "Canada:F",
    "Canada:G",
    "Canada:NC-17",
    "Canada:PA",
    "Canada:PG",
    "Canada:PG-13",
    "Canada:R",
    "Canada:RX",
    "Canada:TV-G",
    "Canada:TV-MA",
    "Canada:TV-PG",
    "Canada:TV-Y",
    "Canada:TV-Y7",
    "Canada:TV-Y7-FV",
    "Canada:TV-14",
    "Canada:XXX",
    "Canada:Not Rated",
    "Chile:(Banned)",
    "Chile:13+",
    "Chile:14",
    "Chile:16+",
    "Chile:18",
    "Chile:A",
    "Chile:F",
    "Chile:I",
    "Chile:I12",
    "Chile:I7",
    "Chile:R",
    "Chile:TE",
    "Chile:TE+7",
    "China:(Banned)",
    "China:13",
    "China:17",
    "Colombia:12",
    "Colombia:15",
    "Colombia:18",
    "Colombia:7",
    "Colombia:T",
    "Colombia:X",
    "Costa Rica:TP",
    "Costa Rica:TP7",
    "Costa Rica:TP12+",
    "Costa Rica:12+",
    "Costa Rica:15+",
    "Costa Rica:18+",
    "Costa Rica:Recomendado",
    "Cyprus:Cat. 3",
    "Czech Republic:12",
    "Czech Republic:15",
    "Czech Republic:18",
    "Czech Republic:8+",
    "Czech Republic:U",
    "Czechoslovakia:(Banned)",
    "Denmark:(Banned)",
    "Denmark:11",
    "Denmark:12",
    "Denmark:15",
    "Denmark:16",
    "Denmark:7",
    "Denmark:A",
    "Ecuador:Not Rated",
    "Ecuador:ALL",
    "Ecuador:A",
    "Ecuador:B",
    "Ecuador:C",
    "Ecuador:TP",
    "Ecuador:7+",
    "Ecuador:12",
    "Ecuador:13+",
    "Ecuador:15",
    "Ecuador:16",
    "Ecuador:18",
    "East Germany:(Banned)",
    "Egypt:(Banned)",
    "Egypt:G",
    "Egypt:E",
    "Egypt:7+",
    "Egypt:8+",
    "Egypt:12+",
    "Egypt:13+",
    "Egypt:16+",
    "Egypt:18+",
    "Egypt:R",
    "Egypt:R-12",
    "Egypt:PG",
    "Egypt:PG-12",
    "Egypt:PG-13",
    "Egypt:Not Rated",
    "Egypt:All ages",
    "Finland:(Banned)",
    "Finland:K-10",
    "Finland:K-10/7",
    "Finland:K-10/8",
    "Finland:K-11",
    "Finland:K-11/9",
    "Finland:K-12",
    "Finland:K-12/9",
    "Finland:K-13",
    "Finland:K-14",
    "Finland:K-15",
    "Finland:K-15/13",
    "Finland:K-16",
    "Finland:K-16/13",
    "Finland:K-18",
    "Finland:K-3",
    "Finland:K-6",
    "Finland:K-6/3",
    "Finland:K-6/4",
    "Finland:K-7",
    "Finland:K-7/4",
    "Finland:K-7/5",
    "Finland:K-8",
    "Finland:K-8/5",
    "Finland:K-8/6",
    "Finland:S/T",
    "Finland:S",
    "France:Accord parental",
    "France:Tous publics",
    "France:Tous publics avec avertissement",
    "France:0+",
    "France:6+",
    "France:7",
    "France:9+",
    "France:10",
    "France:10 avec avertissement",
    "France:12",
    "France:12 avec avertissement",
    "France:13",
    "France:14+",
    "France:16",
    "France:16 avec avertissement",
    "France:18",
    "France:X",
    "France:(Banned)",
    "France:Not Rated",
    "France:Public Averti",
    "Germany:(Banned)",
    "Germany:0",
    "Germany:12",
    "Germany:13",
    "Germany:16",
    "Germany:18",
    "Germany:6",
    "Germany:Infoprogramm gemäß § 14 JuSchG",
    "Germany:Not Rated",
    "Greece:A-18",
    "Greece:K",
    "Greece:K-8",
    "Greece:K-10",
    "Greece:K-12",
    "Greece:K-13",
    "Greece:K-15",
    "Greece:K-16",
    "Greece:K-17",
    "Hong Kong:Not Rated",
    "Hong Kong::All",
    "Hong Kong:I",
    "Hong Kong:II",
    "Hong Kong:IIA",
    "Hong Kong:IIB",
    "Hong Kong:III",
    "Hong Kong:7+",
    "Hong Kong:13+",
    "Hong Kong:16+",
    "Hong Kong:18+",
    "Hungary:12",
    "Hungary:14",
    "Hungary:16",
    "Hungary:18",
    "Hungary:6",
    "Hungary:KN",
    "Iceland:(Banned)",
    "Iceland:10",
    "Iceland:12",
    "Iceland:14",
    "Iceland:16",
    "Iceland:18",
    "Iceland:7",
    "Iceland:L",
    "Iceland:LH",
    "Iceland:Unrated",
    "India:(Banned)",
    "India:All",
    "India:A",
    "India:PG",
    "India:U",
    "India:UA",
    "India:UA 7+",
    "India:UA 13+",
    "India:UA 16+",
    "India:7",
    "India:12+",
    "India:13",
    "India:15+",
    "India:16",
    "India:18",
    "India:Not Rated",
    "Indonesia:Not Rated",
    "Indonesia:PG",
    "Indonesia:7+",
    "Indonesia:13+",
    "Indonesia:15",
    "Indonesia:16+",
    "Indonesia:17+",
    "Indonesia:18+",
    "Indonesia:20+",
    "Indonesia:21",
    "Indonesia:21+",
    "Indonesia:A",
    "Indonesia:D",
    "Indonesia:D17+",
    "Indonesia:D21+",
    "Indonesia:P",
    "Indonesia:R",
    "Indonesia:G",
    "Indonesia:R13+",
    "Indonesia:SU",
    "Indonesia:R:BO",
    "Indonesia:A:BO",
    "Indonesia:P:BO",
    "Indonesia:Semua",
    "Iran:(Banned)",
    "Iran:18+",
    "Iraq:(Banned)",
    "Ireland:(Banned)",
    "Ireland:12",
    "Ireland:12A",
    "Ireland:12PG",
    "Ireland:12RA",
    "Ireland:15",
    "Ireland:15A",
    "Ireland:15PG",
    "Ireland:16",
    "Ireland:18",
    "Ireland:G",
    "Ireland:PG",
    "Israel:ALL",
    "Israel:Not Rated",
    "Israel:7+",
    "Israel:8+",
    "Israel:12",
    "Israel:13",
    "Israel:14",
    "Israel:15+",
    "Israel:16",
    "Israel:18",
    "Israel:PG",
    "Israel:X",
    "Italy:(Banned)",
    "Italy:T",
    "Italy: BA",
    "Italy:Not Rated",
    "Italy:VM12",
    "Italy:VM14",
    "Italy:VM16",
    "Italy:VM18",
    "Italy:6+",
    "Japan:Not Rated",
    "Japan:(Banned)",
    "Japan:12",
    "Japan:15",
    "Japan:16+",
    "Japan:18",
    "Japan:A",
    "Japan:Adult Movie",
    "Japan:All Ages",
    "Japan:B",
    "Japan:C",
    "Japan:D",
    "Japan:G",
    "Japan:PG-12",
    "Japan:PG12",
    "Japan:R",
    "Japan:R-15",
    "Japan:R-18",
    "Japan:R15+",
    "Japan:R18+",
    "Japan:Unrated",
    "Japan:Z",
    "Kuwait:(Banned)",
    "Lebanon:(Banned)",
    "Lithuania:N-13",
    "Lithuania:N-16",
    "Lithuania:N-18",
    "Lithuania:N-7",
    "Lithuania:V",
    "Luxembourg:12",
    "Luxembourg:16",
    "Luxembourg:17",
    "Luxembourg:18",
    "Luxembourg:6",
    "Luxembourg:A",
    "Malaysia:(Banned)",
    "Malaysia:18",
    "Malaysia:18PL",
    "Malaysia:18SG",
    "Malaysia:18SX",
    "Malaysia:P13",
    "Malaysia:U",
    "Maldives:(Banned)",
    "Maldives:12+",
    "Maldives:15+",
    "Maldives:18+",
    "Maldives:18+R",
    "Maldives:G",
    "Maldives:PG",
    "Maldives:PU",
    "Malta:12",
    "Malta:12A",
    "Malta:15",
    "Malta:16",
    "Malta:18",
    "Malta:PG",
    "Malta:U",
    "Mexico:A",
    "Mexico:AA",
    "Mexico:B",
    "Mexico:B15",
    "Mexico:C",
    "Mexico:D",
    "Mexico: G",
    "Mexico:TV-Y",
    "Mexico:TV-G",
    "Mexico:PG",
    "Mexico:TV-Y7",
    "Mexico:TV-Y7-FV",
    "Mexico:TV-PG",
    "Mexico:PG-13",
    "Mexico:TV-14",
    "Mexico:R",
    "Mexico:NC-17",
    "Mexico:TV-MA",
    "Mexico:S/C",
    "Mexico:0+",
    "Mexico:9+",
    "Mexico:12+",
    "Mexico:18+",
    "Mexico:TODO",
    "Mexico:7",
    "Mexico:13",
    "Mexico:16",
    "Mexico:18",
    "Mongolia:PG",
    "Netherlands:12",
    "Netherlands:14",
    "Netherlands:16",
    "Netherlands:18",
    "Netherlands:6",
    "Netherlands:7+",
    "Netherlands:9",
    "Netherlands:13+",
    "Netherlands:AL",
    "Netherlands:MG6",
    "Netherlands:Unrated",
    "New Zealand:AO",
    "New Zealand:(Banned)",
    "New Zealand:G",
    "New Zealand:M",
    "New Zealand:Objectionable",
    "New Zealand:PG",
    "New Zealand:R",
    "New Zealand:R13",
    "New Zealand:R15",
    "New Zealand:R16",
    "New Zealand:R18",
    "New Zealand:RP13",
    "New Zealand:RP16",
    "New Zealand:RP18",
    "Nigeria:12",
    "Nigeria:12A",
    "Nigeria:15",
    "Nigeria:18",
    "Nigeria:G",
    "Nigeria:PG",
    "Nigeria:RE",
    "Norway:(Banned)",
    "Norway:10",
    "Norway:11",
    "Norway:12",
    "Norway:15",
    "Norway:16",
    "Norway:18",
    "Norway:5",
    "Norway:7",
    "Norway:9",
    "Norway:A",
    "Norway:Banned",
    "Peru:14",
    "Peru:18",
    "Peru:Apt",
    "Philippines :All",
    "Philippines:(Banned)",
    "Philippines:G",
    "Philippines :PG",
    "Philippines:PG-13",
    "Philippines:R-13",
    "Philippines:R-16",
    "Philippines:R-18",
    "Philippines :7+",
    "Philippines :13+",
    "Philippines :14",
    "Philippines :16+",
    "Philippines :18+",
    "Philippines:SPG",
    "Philippines:U",
    "Philippines:X",
    "Poland:(Banned)",
    "Poland:All",
    "Poland:0",
    "Poland:6",
    "Poland:10+",
    "Poland:12",
    "Poland:13",
    "Poland:15",
    "Poland:16",
    "Poland:18",
    "Poland:7",
    "Poland:b.o.",
    "Poland:NC",
    "Poland:G",
    "Portugal:(Banned)",
    "Portugal:10AP",
    "Portugal:12AP",
    "Portugal:16",
    "Portugal:17",
    "Portugal:M/12",
    "Portugal:M/14",
    "Portugal:M/16",
    "Portugal:M/18",
    "Portugal:M/3",
    "Portugal:M/4",
    "Portugal:M/6",
    "Portugal:T",
    "Puerto Rico:PG",
    "Puerto Rico:PG-13",
    "Romania:A.G.",
    "Romania:I.C.-14",
    "Romania:I.M.-18",
    "Russia:(Banned)",
    "Russia:0+",
    "Russia:12+",
    "Russia:14+",
    "Russia:16+",
    "Russia:18+",
    "Russia:6+",
    "Saudi Arabia:R18",
    "Saudi Arabia:R15",
    "Saudi Arabia:R12",
    "Saudi Arabia:PG12",
    "Saudi Arabia:PG",
    "Saudi Arabia:G",
    "Saudi Arabia:Not Rated",
    "Saudi Arabia:(Banned)",
    "Serbia:12",
    "Singapore:(Banned)",
    "Singapore:ADV",
    "Singapore:ADV16",
    "Singapore:G",
    "Singapore:15",
    "Singapore:M18",
    "Singapore:NC-16",
    "Singapore:NC16",
    "Singapore:PG",
    "Singapore:PG13",
    "Singapore:R(A)",
    "Singapore:R21",
    "Singapore:Unrated",
    "Slovakia:12",
    "Slovenia:15+",
    "South Africa:(Banned)",
    "South Africa:(Seized)",
    "South Africa:10",
    "South Africa:10-12",
    "South Africa:10-12PG",
    "South Africa:13",
    "South Africa:16",
    "South Africa:18",
    "South Africa:7-9",
    "South Africa:7-9PG",
    "South Africa:A",
    "South Africa:PG",
    "South Africa:X18",
    "South Africa:XX",
    "South Korea:(Banned)",
    "South Korea:12",
    "South Korea:15",
    "South Korea:18",
    "South Korea:19",
    "South Korea:7",
    "South Korea:All",
    "South Korea:Limited",
    "South Korea:Youth not allowed",
    "South Korea:13+",
    "South Korea:16+",
    "Soviet Union:(Banned)",
    "Soviet Union:16",
    "Spain:A",
    "Spain:A/fig",
    "Spain:A/i",
    "Spain:A/i/fig",
    "Spain:TP",
    "Spain:0+",
    "Spain:3",
    "Spain:4+",
    "Spain:6+",
    "Spain:7",
    "Spain:7/fig",
    "Spain:7/i",
    "Spain:7/i/fig",
    "Spain:9+",
    "Spain:10",
    "Spain:12",
    "Spain:12/fig",
    "Spain:13",
    "Spain:14",
    "Spain:16",
    "Spain:16/fig",
    "Spain:18",
    "Spain:18/fig",
    "Spain:S",
    "Spain:X",
    "Spain: Apta para mayores",
    "Spain:Not Rated",
    "Spain:(Banned)",
    "Sweden:(Banned)",
    "Sweden:All",
    "Sweden:Alla",
    "Sweden:0+",
    "Sweden:7",
    "Sweden:7+",
    "Sweden:9",
    "Sweden:9+",
    "Sweden:10+",
    "Sweden:11",
    "Sweden:12",
    "Sweden:13",
    "Sweden:14",
    "Sweden:15",
    "Sweden:16+",
    "Sweden:18",
    "Sweden:18+",
    "Sweden:Btl",
    "Sweden:IK",
    "Sweden:OK",
    "Switzerland:0",
    "Switzerland:10",
    "Switzerland:12",
    "Switzerland:14",
    "Switzerland:16",
    "Switzerland:18",
    "Switzerland:6",
    "Switzerland:7",
    "Switzerland:8",
    "Switzerland:9",
    "Taiwan:ALL",
    "Taiwan:6+",
    "Taiwan:7+",
    "Taiwan:13+",
    "Taiwan:16+",
    "Taiwan:18+",
    "Taiwan:G",
    "Taiwan:P",
    "Taiwan:R",
    "Taiwan:GP",
    "Taiwan:PG-12",
    "Taiwan:R-12",
    "Taiwan:R-15",
    "Taiwan:R-18",
    "Taiwan:PG",
    "Taiwan:PG-15",
    "Thailand:ALL",
    "Thailand:(Banned)",
    "Thailand:Not Rated",
    "Thailand:C",
    "Thailand:E",
    "Thailand:G",
    "Thailand:U",
    "Thailand:3+",
    "Thailand:6+",
    "Thailand:7+",
    "Thailand:13",
    "Thailand:13+",
    "Thailand:15",
    "Thailand:15+",
    "Thailand:16+",
    "Thailand:18",
    "Thailand:18+",
    "Thailand:20",
    "Thailand:G",
    "Thailand:P",
    "Thailand:PG-13",
    "Thailand:PD-14",
    "Thailand:R-14",
    "Turkey:Not Rated",
    "Turkey:Genel İzleyici Kitlesi",
    "Turkey:6A",
    "Turkey:6+",
    "Turkey:7A",
    "Turkey:10A",
    "Turkey:10+",
    "Turkey:13+",
    "Turkey:13A",
    "Turkey:15+",
    "Turkey:15A",
    "Turkey:16+",
    "Turkey:18+",
    "Turkey:7+",
    "Turkey:G",
    "UK:(Banned)",
    "UK:Caution",
    "UK:0+",
    "UK:3+",
    "UK:6+",
    "UK:7+",
    "UK:9+",
    "UK:11+",
    "UK:12",
    "UK:12A",
    "UK:13+",
    "UK:14+",
    "UK:15",
    "UK:16",
    "UK:18",
    "UK:7",
    "UK:A",
    "UK:AA",
    "UK:All",
    "UK:Adult",
    "UK:E",
    "UK:G",
    "UK:H",
    "UK:Mature",
    "UK:Not Rated",
    "UK:NR",
    "UK:PG",
    "UK:PG-13",
    "UK:R18",
    "UK:Rejected",
    "UK:Teen",
    "UK:U",
    "UK:Uc",
    "UK:X",
    "Ukraine:12",
    "Ukraine:16",
    "Ukraine:18",
    "Ukraine:DA",
    "Ukraine:ZA",
    "Ukraine:(Banned)",
    "United Arab Emirates:All",
    "United Arab Emirates:G",
    "United Arab Emirates:PG",
    "United Arab Emirates:0+",
    "United Arab Emirates:7+",
    "United Arab Emirates:12+",
    "United Arab Emirates:13+",
    "United Arab Emirates:15+",
    "United Arab Emirates:16+",
    "United Arab Emirates:18+",
    "United Arab Emirates:TBA-15+",
    "United Arab Emirates:PG-12",
    "United Arab Emirates:PG-13",
    "United Arab Emirates:PG-15",
    "United Arab Emirates:R",
    "United Arab Emirates:16D",
    "United Arab Emirates:FAM",
    "United Arab Emirates:PG-12",
    "United Arab Emirates:U",
    "United Arab Emirates:18TC",
    "United Arab Emirates:TBC",
    "United Arab Emirates:Not Rated",
    "USA:12",
    "USA:AO",
    "USA:Approved",
    "USA:Banned",
    "USA:EC",
    "USA:E",
    "USA:E10+",
    "USA:G",
    "USA:GA",
    "USA:GP",
    "USA:K-A",
    "USA:M",
    "USA:M/PG",
    "USA:MA-13",
    "USA:MA-17",
    "USA:NC-17",
    "USA:Not Rated",
    "USA:Open",
    "USA:Passed",
    "USA:PG",
    "USA:PG-13",
    "USA:R",
    "USA:T",
    "USA:TV-13",
    "USA:TV-14",
    "USA:TV-G",
    "USA:TV-MA",
    "USA:TV-PG",
    "USA:TV-Y",
    "USA:TV-Y7",
    "USA:TV-Y7-FV",
    "USA:Unrated",
    "USA:X",
    "Venezuela:PG-13",
    "Vietnam:(Banned)",
    "Vietnam:P",
    "Vietnam:C13",
    "Vietnam:C16",
    "Vietnam:C18",
    "West Germany:(Banned)",
    "West Germany:0",
    "West Germany:12",
    "West Germany:16",
    "West Germany:18",
    "West Germany:6",
    "West Germany:Not Rated"
);

$sound_mix = array(
    "Mono",
    "Stereo",
    "Silent",
    "Dolby Digital",
    "Dolby",
    "Dolby SR",
    "DTS",
    "SDDS",
    "12-Track Digital Sound",
    "3 Channel Stereo",
    "4-Track Stereo",
    "6-Track Stereo",
    "70 mm 6-Track",
    "Afifa Ton-Kopie",
    "AGA Sound System",
    "Animatophone",
    "Auro 11.1",
    "Auro 9.1",
    "Aurofone",
    "B.A.F. Sound System",
    "Blue Seal Noiseless Recording",
    "Bristolphone",
    "Broadway Surround",
    "CDS",
    "Chace Surround",
    "Chronophone",
    "Cinematophone",
    "Cineophone",
    "Cinephone",
    "Cinerama 7-Track",
    "Cinesound",
    "D-Cinema 48kHz 5.1",
    "D-Cinema 48kHz 7.1",
    "D-Cinema 48kHz Dolby Surround 7.1",
    "D-Cinema 96kHz 5.1",
    "D-Cinema 96kHz 7.1",
    "D-Cinema 96kHz Dolby Surround 7.1",
    "Datasat",
    "De Forest Phonofilm",
    "Digitrac Digital Audio System",
    "Dolby",
    "Dolby Atmos",
    "Dolby Digital",
    "Dolby Digital EX",
    "Dolby SR",
    "Dolby Stereo",
    "Dolby Surround 7.1",
    "DTS",
    "DTS 70 mm",
    "DTS-8",
    "DTS-ES",
    "DTS-Stereo",
    "DX Stereo",
    "Filmtone",
    "Full Range Recording System",
    "Gaumontphone",
    "IMAX 6-Track",
    "International Recording Engineers System",
    "Iwerks Digital Audio",
    "Kinetophone",
    "Kinopanorama 9-Track",
    "Kinoplasticon",
    "Klangfilm Magnetocord",
    "Klangfilm-Stereocord",
    "LC-Concept Digital Sound",
    "Li-Westrex System",
    "Magnaphone Western Electric",
    "Magnetocord",
    "Matrix Surround",
    "Mono",
    "Optiphone",
    "Ortiphone",
    "Perspecta Stereo",
    "Phillips Sound",
    "Phono-Cinema-Theatre",
    "Phono-Kinema",
    "Phonofilm",
    "Pulvári System",
    "Quadrophonic",
    "Quintaphonic",
    "SDDS",
    "Sensurround",
    "Servotron Stereo",
    "Silent",
    "Sonics",
    "Sonics-DDP",
    "Sonix",
    "Sonora-Bristolphone",
    "Sound 360°",
    "Sound Trax Surround Stereo",
    "Soundelux",
    "Spectra-Stereo",
    "Stereo",
    "Super Space Sound",
    "Synchrotone",
    "Synthetic",
    "Systemi A. Shorin",
    "Système Cottet",
    "Tagephone",
    "TMH Labs 10.2 Channel Sound",
    "Tri-Ergon Sound System",
    "Ultra Stereo",
    "Variray Blue Seal Recording",
    "Visatone",
    "Vistasonic",
    "Vitaphone",
    "Vivaphone",
    "Wicmar and Blue Seal Noiseless Recording"
);

$sound_mix_attribute = array(
    "(RCA Sound Recording)",
    "(Westrex Recording System)",
    "(RCA Sound System)",
    "(Western Electric Recording)",
    "(Western Electric Sound System)",
    "Other (use box below)"
);

$aspect_ratio = array(
    "1.33 : 1",
    "16:9 HD",
    "2.35 : 1",
    "1.85 : 1",
    "1.37 : 1",
    "1.78 : 1",
    "4:3",
    "1.66 : 1",
    "1.78 : 1 / (high definition)",
    "16 : 9",
    "Other (use box below)"
);
